'''
Classes from the 'AccessibilityUtilities' framework.
'''

try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None

    
AXResourceLoader = _Class('AXResourceLoader')
AXCharacterSoundMap = _Class('AXCharacterSoundMap')
AXSiriShortcutsManager = _Class('AXSiriShortcutsManager')
AXSiriShortcut = _Class('AXSiriShortcut')
AXSettingsObjectDestructionHelper = _Class('AXSettingsObjectDestructionHelper')
AXMouseEventListener = _Class('AXMouseEventListener')
AXSwitch = _Class('AXSwitch')
AXMIDIDeviceEntity = _Class('AXMIDIDeviceEntity')
AXBuddyDataPackage = _Class('AXBuddyDataPackage')
AXEventProcessor = _Class('AXEventProcessor')
AXReplayer = _Class('AXReplayer')
AXLogColorizer = _Class('AXLogColorizer')
AXEventData = _Class('AXEventData')
AXEventGameControllerInfoRepresentation = _Class('AXEventGameControllerInfoRepresentation')
AXSystemAppServer = _Class('AXSystemAppServer')
AXMIDIManager = _Class('AXMIDIManager')
AXActionCoalescer = _Class('AXActionCoalescer')
AXUpdateElementVisualsCoalescer = _Class('AXUpdateElementVisualsCoalescer')
AXIndexMap = _Class('AXIndexMap')
AXReplayableGesture = _Class('AXReplayableGesture')
AXPageTurningReplayableGesture = _Class('AXPageTurningReplayableGesture')
AXCenterTapReplayableGesture = _Class('AXCenterTapReplayableGesture')
AXMutableReplayableGesture = _Class('AXMutableReplayableGesture')
AXNamedReplayableGesture = _Class('AXNamedReplayableGesture')
AXCodeItem = _Class('AXCodeItem')
AXMIDIParser = _Class('AXMIDIParser')
AXAlternativeVoices = _Class('AXAlternativeVoices')
AXTapticSoundTestingContainer = _Class('AXTapticSoundTestingContainer')
AXTapticTimeManager = _Class('AXTapticTimeManager')
AXSettings = _Class('AXSettings')
AXEventRepresentation = _Class('AXEventRepresentation')
AXEventKeyInfoRepresentation = _Class('AXEventKeyInfoRepresentation')
AXThreadTimer = _Class('AXThreadTimer')
AXThreadTimerTask = _Class('AXThreadTimerTask')
AXLanguageTaggedContent = _Class('AXLanguageTaggedContent')
AXLanguageTag = _Class('AXLanguageTag')
AXLanguageManager = _Class('AXLanguageManager')
AXDialectMap = _Class('AXDialectMap')
AXSwitchRecipe = _Class('AXSwitchRecipe')
AXSwitchRecipeMapping = _Class('AXSwitchRecipeMapping')
AXSwitchRegistrar = _Class('AXSwitchRegistrar')
AXLangMap = _Class('AXLangMap')
AXARDescriptionFormatting = _Class('AXARDescriptionFormatting')
NonRetainedObjectContainer = _Class('NonRetainedObjectContainer')
AXAppRepresentation = _Class('AXAppRepresentation')
AXOrator = _Class('AXOrator')
AXAudioHardwareManager = _Class('AXAudioHardwareManager')
AXPathWrapper = _Class('AXPathWrapper')
AXTrampoline = _Class('AXTrampoline')
AXEventAccelerometerInfoRepresentation = _Class('AXEventAccelerometerInfoRepresentation')
AXCodeLoader = _Class('AXCodeLoader')
AXEventPathInfoRepresentation = _Class('AXEventPathInfoRepresentation')
AXValidationManager = _Class('AXValidationManager')
AXVoiceOverActivity = _Class('AXVoiceOverActivity')
AXMobileConfigurationInterface = _Class('AXMobileConfigurationInterface')
AXBinaryMonitor = _Class('AXBinaryMonitor')
AXMIDIDevice = _Class('AXMIDIDevice')
AXMIDIEvent = _Class('AXMIDIEvent')
AXMIDIDeviceEntityEndpoint = _Class('AXMIDIDeviceEntityEndpoint')
AXLoggingSubsystem = _Class('AXLoggingSubsystem')
AXSubsystemAXSoundBoard = _Class('AXSubsystemAXSoundBoard')
AXSubsystemAXCustomizableMouse = _Class('AXSubsystemAXCustomizableMouse')
AXSubsystemSpeakFingerManager = _Class('AXSubsystemSpeakFingerManager')
AXSubsystemIPC = _Class('AXSubsystemIPC')
AXSubsystemSBServer = _Class('AXSubsystemSBServer')
AXSubsystemBBServer = _Class('AXSubsystemBBServer')
AXSubsystemAXUIViewService = _Class('AXSubsystemAXUIViewService')
AXSubsystemAXSettings = _Class('AXSubsystemAXSettings')
AXSubsystemInvertColors = _Class('AXSubsystemInvertColors')
AXSubsystemDataMigrator = _Class('AXSubsystemDataMigrator')
AXSubsystemBrokenHomeButton = _Class('AXSubsystemBrokenHomeButton')
AXSubsystemMagicTapToggle = _Class('AXSubsystemMagicTapToggle')
AXSubsystemAXAggregateLogging = _Class('AXSubsystemAXAggregateLogging')
AXSubsystemAXCharacterVoices = _Class('AXSubsystemAXCharacterVoices')
AXSubsystemAXVectorKit = _Class('AXSubsystemAXVectorKit')
AXSubsystemAXNotifications = _Class('AXSubsystemAXNotifications')
AXSubsystemVoiceOver = _Class('AXSubsystemVoiceOver')
AXSubsystemMagnifierBright = _Class('AXSubsystemMagnifierBright')
AXSubsystemMagnifier = _Class('AXSubsystemMagnifier')
AXSubsystemVoiceOverLifeCycle = _Class('AXSubsystemVoiceOverLifeCycle')
AXSubsystemVoiceOverIAP = _Class('AXSubsystemVoiceOverIAP')
AXSubsystemSwitchControlHardware = _Class('AXSubsystemSwitchControlHardware')
AXSubsystemBrailleHardware = _Class('AXSubsystemBrailleHardware')
AXSubsystemSCPauseResume = _Class('AXSubsystemSCPauseResume')
AXSubsystemPronunciations = _Class('AXSubsystemPronunciations')
AXSubsystemSCElementNav = _Class('AXSubsystemSCElementNav')
AXSubsystemContextKit = _Class('AXSubsystemContextKit')
AXSubsystemSpeakThis = _Class('AXSubsystemSpeakThis')
AXSubsystemSpeakTyping = _Class('AXSubsystemSpeakTyping')
AXSubsystemSpeakSelection = _Class('AXSubsystemSpeakSelection')
AXSubsystemLocCaptionPanel = _Class('AXSubsystemLocCaptionPanel')
AXSubsystemAudioRouting = _Class('AXSubsystemAudioRouting')
AXSubsystemVisualAlerts = _Class('AXSubsystemVisualAlerts')
AXSubsystemBrailleGestures = _Class('AXSubsystemBrailleGestures')
AXSubsystemVOTAudio = _Class('AXSubsystemVOTAudio')
AXSubsystemVOTiCloud = _Class('AXSubsystemVOTiCloud')
AXSubsystemAVSpeechSynthesis = _Class('AXSubsystemAVSpeechSynthesis')
AXSubsystemZoom = _Class('AXSubsystemZoom')
AXSubsystemSpeechAssetDownloader = _Class('AXSubsystemSpeechAssetDownloader')
AXSubsystemUserInterfaceService = _Class('AXSubsystemUserInterfaceService')
AXSubsystemEventTap = _Class('AXSubsystemEventTap')
AXDeviceMonitor = _Class('AXDeviceMonitor')
AXIPCClient = _Class('AXIPCClient')
AXIPCOutstandingAsyncRequest = _Class('AXIPCOutstandingAsyncRequest')
AXPostConnectionTask = _Class('AXPostConnectionTask')
AXIPCServer = _Class('AXIPCServer')
AXIPCServerMessageHandlerContext = _Class('AXIPCServerMessageHandlerContext')
AXIPCServerClientRegistration = _Class('AXIPCServerClientRegistration')
AXUserEventTimer = _Class('AXUserEventTimer')
AXValueChangeUtilities = _Class('AXValueChangeUtilities')
FKAAvailableCommands = _Class('FKAAvailableCommands')
AXAssertion = _Class('AXAssertion')
AXSynchronousAssertion = _Class('AXSynchronousAssertion')
AXEventListenerContainer = _Class('AXEventListenerContainer')
AXEventPointerInfoRepresentation = _Class('AXEventPointerInfoRepresentation')
AXAssertionWorkItem = _Class('AXAssertionWorkItem')
AXFirstResponderValueChangeManager = _Class('AXFirstResponderValueChangeManager')
AXRedirectedEventDetector = _Class('AXRedirectedEventDetector')
AXEventIOSMACPointerInfoRepresentation = _Class('AXEventIOSMACPointerInfoRepresentation')
AXAssertionCoordinator = _Class('AXAssertionCoordinator')
AXAirPodSettingsManager = _Class('AXAirPodSettingsManager')
AXSpringBoardActionHandlerHolder = _Class('AXSpringBoardActionHandlerHolder')
AXEventTapManager = _Class('AXEventTapManager')
AXEventTapPair = _Class('AXEventTapPair')
AXCustomizableMouse = _Class('AXCustomizableMouse')
AXPredictiveTypingModel = _Class('AXPredictiveTypingModel')
AXTypingPrediction = _Class('AXTypingPrediction')
AXDisplayLinkManager = _Class('AXDisplayLinkManager')
AXDisplayLinkManagerTargetAction = _Class('AXDisplayLinkManagerTargetAction')
AXIPCMessage = _Class('AXIPCMessage')
AXEventHandInfoRepresentation = _Class('AXEventHandInfoRepresentation')
AXTripleClickHelpers = _Class('AXTripleClickHelpers')
AXServer = _Class('AXServer')
AXVoiceOverServer = _Class('AXVoiceOverServer')
AXBackBoardServer = _Class('AXBackBoardServer')
AXSpringBoardServer = _Class('AXSpringBoardServer')
AXPerformanceTestReportingServer = _Class('AXPerformanceTestReportingServer')
FKASiriShortcutKeyboardCommand = _Class('FKASiriShortcutKeyboardCommand')
AVSiriFemaleSpeechSynthesisVoice = _Class('AVSiriFemaleSpeechSynthesisVoice')
AVSiriMaleSpeechSynthesisVoice = _Class('AVSiriMaleSpeechSynthesisVoice')
AVAlexSpeechSynthesisVoice = _Class('AVAlexSpeechSynthesisVoice')
