'''
Classes from the 'CoreUI' framework.
'''

try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None

    
CUIPSDLayerEffectComponent = _Class('CUIPSDLayerEffectComponent')
CUIPSDLayerEffectBevelEmboss = _Class('CUIPSDLayerEffectBevelEmboss')
CUIPSDLayerEffectGradientOverlay = _Class('CUIPSDLayerEffectGradientOverlay')
CUIPSDLayerEffectColorOverlay = _Class('CUIPSDLayerEffectColorOverlay')
CUIPSDLayerEffectOuterGlow = _Class('CUIPSDLayerEffectOuterGlow')
CUIPSDLayerEffectInnerGlow = _Class('CUIPSDLayerEffectInnerGlow')
CUIPSDLayerEffectInnerShadow = _Class('CUIPSDLayerEffectInnerShadow')
CUIPSDLayerEffectDropShadow = _Class('CUIPSDLayerEffectDropShadow')
CUIPSDLayerEffects = _Class('CUIPSDLayerEffects')
CUIShapeEffectStack = _Class('CUIShapeEffectStack')
CUITextEffectStack = _Class('CUITextEffectStack')
CUIThemeSchemaLayer = _Class('CUIThemeSchemaLayer')
CUIPSDLayer = _Class('CUIPSDLayer')
CUIPSDLayerGroupEnd = _Class('CUIPSDLayerGroupEnd')
CUIPSDLayerGroupStart = _Class('CUIPSDLayerGroupStart')
CUIPSDGradientLayer = _Class('CUIPSDGradientLayer')
CUIPSDImageLayer = _Class('CUIPSDImageLayer')
CUIPSDLayoutMetricsChannel = _Class('CUIPSDLayoutMetricsChannel')
CUINamedImageDescription = _Class('CUINamedImageDescription')
CUIThemeSchemaPSDLayer = _Class('CUIThemeSchemaPSDLayer')
CUIThemeSchemaPSDLayerGroup = _Class('CUIThemeSchemaPSDLayerGroup')
CUIThemeSchemaPSDRenditionLayer = _Class('CUIThemeSchemaPSDRenditionLayer')
CUIThemeSchemaRenditionGroup = _Class('CUIThemeSchemaRenditionGroup')
CUIThemeSchema = _Class('CUIThemeSchema')
CoreUI = _Class('CoreUI')
CSITextureHelper = _Class('CSITextureHelper')
CSIATECHelper = _Class('CSIATECHelper')
CUIThemeGradient = _Class('CUIThemeGradient')
CUIShapeEffectPreset = _Class('CUIShapeEffectPreset')
CUIThemeDataEffectPreset = _Class('CUIThemeDataEffectPreset')
CUIPSLayerEffectsPreset = _Class('CUIPSLayerEffectsPreset')
CUIColor = _Class('CUIColor')
CUIImage = _Class('CUIImage')
CUIMeshBuffer = _Class('CUIMeshBuffer')
CUIPSDLayerMaskRef = _Class('CUIPSDLayerMaskRef')
CUIPSDLayerBaseRef = _Class('CUIPSDLayerBaseRef')
CUIPSDLayerGroupRef = _Class('CUIPSDLayerGroupRef')
CUIPSDLayerRef = _Class('CUIPSDLayerRef')
CUIPSDImageRef = _Class('CUIPSDImageRef')
CUIMutablePSDImageRef = _Class('CUIMutablePSDImageRef')
CUIPSDGradientEvaluator = _Class('CUIPSDGradientEvaluator')
CUIPSDGradientStop = _Class('CUIPSDGradientStop')
CUIPSDGradientOpacityStop = _Class('CUIPSDGradientOpacityStop')
CUIPSDGradientDoubleOpacityStop = _Class('CUIPSDGradientDoubleOpacityStop')
CUIPSDGradientColorStop = _Class('CUIPSDGradientColorStop')
CUIPSDGradientDoubleColorStop = _Class('CUIPSDGradientDoubleColorStop')
CUIRenditionLayerReference = _Class('CUIRenditionLayerReference')
CUIPSDGradient = _Class('CUIPSDGradient')
CSIBitmapWrapper = _Class('CSIBitmapWrapper')
CSIGenerator = _Class('CSIGenerator')
CUIPattern = _Class('CUIPattern')
CUIStyleEffectConfiguration = _Class('CUIStyleEffectConfiguration')
CUIBackgroundStyleEffectConfiguration = _Class('CUIBackgroundStyleEffectConfiguration')
CUIRenditionSliceInformation = _Class('CUIRenditionSliceInformation')
CSIHelper = _Class('CSIHelper')
CUINamedLookup = _Class('CUINamedLookup')
CUINamedModel = _Class('CUINamedModel')
CUINamedMultisizeImageSet = _Class('CUINamedMultisizeImageSet')
CUINamedExternalLink = _Class('CUINamedExternalLink')
CUINamedTexture = _Class('CUINamedTexture')
CUITextStyle = _Class('CUITextStyle')
CUINamedRecognitionGroup = _Class('CUINamedRecognitionGroup')
CUINamedData = _Class('CUINamedData')
CUINamedRecognitionObject = _Class('CUINamedRecognitionObject')
CUINamedImageAtlas = _Class('CUINamedImageAtlas')
CUINamedRecognitionImage = _Class('CUINamedRecognitionImage')
CUINamedVectorGlyph = _Class('CUINamedVectorGlyph')
CUINamedColor = _Class('CUINamedColor')
CUINamedVectorImage = _Class('CUINamedVectorImage')
CUINamedVectorSVGImage = _Class('CUINamedVectorSVGImage')
CUINamedVectorPDFImage = _Class('CUINamedVectorPDFImage')
CUINamedLayerStack = _Class('CUINamedLayerStack')
CUINamedImage = _Class('CUINamedImage')
CUINamedLayerImage = _Class('CUINamedLayerImage')
CUINamedMultisizeImage = _Class('CUINamedMultisizeImage')
CUIRenditionMetrics = _Class('CUIRenditionMetrics')
CUIThemeRendition = _Class('CUIThemeRendition')
CUIMutableThemeRendition = _Class('CUIMutableThemeRendition')
CUIThemeSchemaEffectRendition = _Class('CUIThemeSchemaEffectRendition')
CUIThemeSchemaRendition = _Class('CUIThemeSchemaRendition')
CUIRuntimeStatistics = _Class('CUIRuntimeStatistics')
CUIRenditionKey = _Class('CUIRenditionKey')
CUINamedRenditionInfo = _Class('CUINamedRenditionInfo')
CUICommonAssetStorage = _Class('CUICommonAssetStorage')
CUIMutableCommonAssetStorage = _Class('CUIMutableCommonAssetStorage')
CUIStructuredThemeStore = _Class('CUIStructuredThemeStore')
CUIMutableStructuredThemeStore = _Class('CUIMutableStructuredThemeStore')
CUIThemeFacet = _Class('CUIThemeFacet')
CUICatalog = _Class('CUICatalog')
CUISystemCatalog = _Class('CUISystemCatalog')
CUIMutableCatalog = _Class('CUIMutableCatalog')
CUIPSDLayerEnumerator = _Class('CUIPSDLayerEnumerator')
