'''
Classes from the 'DataDetectorsUI' framework.
'''

try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None

    
DDCoreRecents = _Class('DDCoreRecents')
DDContextMenuAction = _Class('DDContextMenuAction')
DDContactUtils = _Class('DDContactUtils')
DDRange = _Class('DDRange')
DDResultTracker = _Class('DDResultTracker')
DDActionController = _Class('DDActionController')
DDEventComponents = _Class('DDEventComponents')
DDActionSuggestionsContext = _Class('DDActionSuggestionsContext')
DDActionNaturalLanguageContext = _Class('DDActionNaturalLanguageContext')
DDDetectionController = _Class('DDDetectionController')
DDRemoteActionContext = _Class('DDRemoteActionContext')
DDRemoteActionViewControllerProvider = _Class('DDRemoteActionViewControllerProvider')
DDRemoteTimeLineViewControllerProvider = _Class('DDRemoteTimeLineViewControllerProvider')
DDAction = _Class('DDAction')
DDSendMailAction = _Class('DDSendMailAction')
DDShowCalendarAction = _Class('DDShowCalendarAction')
DDAddEventAction = _Class('DDAddEventAction')
DDCreateEventAction = _Class('DDCreateEventAction')
DDDirectionsAction = _Class('DDDirectionsAction')
DDOpenMapsAction = _Class('DDOpenMapsAction')
DDAddressAction = _Class('DDAddressAction')
DDAddToAddressBookAction = _Class('DDAddToAddressBookAction')
DDTelephoneNumberAction = _Class('DDTelephoneNumberAction')
DDTextMessageAction = _Class('DDTextMessageAction')
DDCallAction = _Class('DDCallAction')
DDFaceTimeAudioAction = _Class('DDFaceTimeAudioAction')
DDFaceTimeAction = _Class('DDFaceTimeAction')
DDCallKitAction = _Class('DDCallKitAction')
DDSingleCallKitAction = _Class('DDSingleCallKitAction')
DDAssistedCallAction = _Class('DDAssistedCallAction')
DDRelayCallAction = _Class('DDRelayCallAction')
DDTTYCallAction = _Class('DDTTYCallAction')
DDShowItemAction = _Class('DDShowItemAction')
DDTrackShipmentAction = _Class('DDTrackShipmentAction')
DDCopyAction = _Class('DDCopyAction')
DDShareAction = _Class('DDShareAction')
DDAddToReadingListAction = _Class('DDAddToReadingListAction')
DDSearchWebAction = _Class('DDSearchWebAction')
DDOpenURLAction = _Class('DDOpenURLAction')
DDMoreActionsAction = _Class('DDMoreActionsAction')
DDMoreCallActionsAction = _Class('DDMoreCallActionsAction')
DDCreateReminderAction = _Class('DDCreateReminderAction')
DDFlightAction = _Class('DDFlightAction')
DDMessagesCustomAction = _Class('DDMessagesCustomAction')
DDPreviewAction = _Class('DDPreviewAction')
DDMoneyPreviewAction = _Class('DDMoneyPreviewAction')
DDClientPreviewAction = _Class('DDClientPreviewAction')
DDParsecAction = _Class('DDParsecAction')
DDParsecPreviewAction = _Class('DDParsecPreviewAction')
DDParsecYeaAction = _Class('DDParsecYeaAction')
DDParsecNayAction = _Class('DDParsecNayAction')
DDNewsPreviewAction = _Class('DDNewsPreviewAction')
DDAppleStorePreviewAction = _Class('DDAppleStorePreviewAction')
DDGenericURLPreviewAction = _Class('DDGenericURLPreviewAction')
DDURLPreviewAction = _Class('DDURLPreviewAction')
DDRemoteAction = _Class('DDRemoteAction')
DDMapAction = _Class('DDMapAction')
DDFlightPreviewAction = _Class('DDFlightPreviewAction')
DDTimeLineAction = _Class('DDTimeLineAction')
DDPersonAction = _Class('DDPersonAction')
DDContextMenuConfiguration = _Class('DDContextMenuConfiguration')
DDRemoteActionViewServiceContext = _Class('DDRemoteActionViewServiceContext')
DDRemoteActionHostContext = _Class('DDRemoteActionHostContext')
DDOperation = _Class('DDOperation')
DDTextKitOperation = _Class('DDTextKitOperation')
DDWebKitOperation = _Class('DDWebKitOperation')
DDFallbackController = _Class('DDFallbackController')
DDParsecLoadingViewController = _Class('DDParsecLoadingViewController')
DDParsecNoDataViewController = _Class('DDParsecNoDataViewController')
DDRemoteActionManagerViewController = _Class('DDRemoteActionManagerViewController')
DDEKDayViewController = _Class('DDEKDayViewController')
DDRemoteActionViewController = _Class('DDRemoteActionViewController')
DDParsecRemoteCollectionViewController = _Class('DDParsecRemoteCollectionViewController')
DDRemoteActionHostViewController = _Class('DDRemoteActionHostViewController')
DDParsecCollectionViewController = _Class('DDParsecCollectionViewController')
DDAddToContactsViewController = _Class('DDAddToContactsViewController')
DDAutoCloseNavigationController = _Class('DDAutoCloseNavigationController')
