'''
Classes from the 'Pyto' framework.
'''

try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None

    
DefinitionsDataSource = _Class('Pyto.DefinitionsDataSource')
ExpansionState = _Class('Pyto.ExpansionState')
Parser = _Class('Pyto.Parser')
PythonLexer = _Class('Pyto.PythonLexer')
ViewControllerStore = _Class('Pyto.ViewControllerStore')
RecentDataSource = _Class('Pyto.RecentDataSource')
CurrentViewStore = _Class('Pyto.CurrentViewStore')
SelectedItemStore = _Class('Pyto.SelectedItemStore')
PyPiIndex = _Class('Pyto.PyPiIndex')
SceneStateStore = _Class('Pyto.SceneStateStore')
MemoryManager = _Class('Pyto.MemoryManager')
Static = _Class('Pyto.Static')
Localizable = _Class('Pyto.Localizable')
BlockBasedSelector = _Class('BlockBasedSelector')
RMProductsRequestDelegate = _Class('RMProductsRequestDelegate')
RMStore = _Class('RMStore')
RMAddPaymentParameters = _Class('RMAddPaymentParameters')
RMStoreAppReceiptVerifier = _Class('RMStoreAppReceiptVerifier')
CaptureDelegate = _Class('CaptureDelegate')
RunCodeIntentHandler = _Class('Pyto.RunCodeIntentHandler')
WidgetView = _Class('Pyto.WidgetView')
InternetConnection = _Class('Pyto.InternetConnection')
PyNotificationCenter = _Class('Pyto.PyNotificationCenter')
BackgroundTask = _Class('Pyto.BackgroundTask')
RunScriptIntentHandler = _Class('Pyto.RunScriptIntentHandler')
RemoteNotifications = _Class('Pyto.RemoteNotifications')
PyExtensionContext = _Class('Pyto.PyExtensionContext')
WidgetComponent = _Class('Pyto.WidgetComponent')
WidgetImage = _Class('Pyto.WidgetImage')
WidgetSymbol = _Class('Pyto.WidgetSymbol')
WidgetText = _Class('Pyto.WidgetText')
WidgetDate = _Class('Pyto.WidgetDate')
NSTemporaryObjectID_default = _Class('NSTemporaryObjectID_default')
NSKVONotifying__UIHyperAsymmetricExtender = _Class('NSKVONotifying__UIHyperAsymmetricExtender')
PyWidget = _Class('Pyto.PyWidget')
WidgetTypeResolutionResult = _Class('WidgetTypeResolutionResult')
WidgetCategoryResolutionResult = _Class('WidgetCategoryResolutionResult')
WidgetCategory = _Class('WidgetCategory')
ScriptIntentResponse = _Class('ScriptIntentResponse')
GetScriptOutputIntentResponse = _Class('GetScriptOutputIntentResponse')
RunCodeIntentResponse = _Class('RunCodeIntentResponse')
RunScriptIntentResponse = _Class('RunScriptIntentResponse')
ScriptIntent = _Class('ScriptIntent')
GetScriptOutputIntent = _Class('GetScriptOutputIntent')
RunCodeIntent = _Class('RunCodeIntent')
RunScriptIntent = _Class('RunScriptIntent')
PyTableViewSection = _Class('Pyto.PyTableViewSection')
PyTextInputTraitsConstants = _Class('Pyto.PyTextInputTraitsConstants')
PyWrapper = _Class('Pyto.PyWrapper')
PyButtonItem = _Class('Pyto.PyButtonItem')
PyGestureRecognizer = _Class('Pyto.PyGestureRecognizer')
PyColor = _Class('Pyto.PyColor')
PyView = _Class('Pyto.PyView')
PyWebView = _Class('Pyto.PyWebView')
PyTextView = _Class('Pyto.PyTextView')
PyImageView = _Class('Pyto.PyImageView')
PyTextField = _Class('Pyto.PyTextField')
PyTableViewCell = _Class('Pyto.PyTableViewCell')
PyTableView = _Class('Pyto.PyTableView')
PyLabel = _Class('Pyto.PyLabel')
PyControl = _Class('Pyto.PyControl')
PySwitch = _Class('Pyto.PySwitch')
PySegmentedControl = _Class('Pyto.PySegmentedControl')
PySlider = _Class('Pyto.PySlider')
PyButton = _Class('Pyto.PyButton')
PyValue = _Class('Pyto.PyValue')
ViewControllerTransitionCoordinator = _Class('Pyto.ViewControllerTransitionCoordinator')
NSKVONotifying__UIHyperConstantExtender = _Class('NSKVONotifying__UIHyperConstantExtender')
NSKVONotifying__UIHyperspace = _Class('NSKVONotifying__UIHyperspace')
NSKVONotifying__UIHyperrectangle = _Class('NSKVONotifying__UIHyperrectangle')
NSKVONotifying__UIHyperregionUnion = _Class('NSKVONotifying__UIHyperregionUnion')
NSKVONotifying__UIHyperpoint = _Class('NSKVONotifying__UIHyperpoint')
MovableTextField = _Class('Pyto.MovableTextField')
FolderDocument = _Class('Pyto.FolderDocument')
PyDocument = _Class('Pyto.PyDocument')
ExtensionsInitializer = _Class('ExtensionsInitializer')
PyCallbackHelper = _Class('Pyto.PyCallbackHelper')
ReviewHelper = _Class('Pyto.ReviewHelper')
_Selector = _Class('Pyto._Selector')
PySelector = _Class('Pyto.PySelector')
QuickLookHelper = _Class('Pyto.QuickLookHelper')
PySpeech = _Class('Pyto.PySpeech')
PyTurtle = _Class('Pyto.PyTurtle')
PyMotionHelper = _Class('Pyto.PyMotionHelper')
PyMultipeerHelper = _Class('Pyto.PyMultipeerHelper')
PyPhotosHelper = _Class('Pyto.PyPhotosHelper')
PyMusicHelper = _Class('Pyto.PyMusicHelper')
PyAlert = _Class('Pyto.PyAlert')
PyFilePicker = _Class('Pyto.PyFilePicker')
PyLocationHelper = _Class('Pyto.PyLocationHelper')
PySharingHelper = _Class('Pyto.PySharingHelper')
PyOutputHelper = _Class('Pyto.PyOutputHelper')
PyInputHelper = _Class('Pyto.PyInputHelper')
PyThread = _Class('Pyto.PyThread')
PyMainThread = _Class('Pyto.PyMainThread')
DeallocationObserver = _Class('DeallocationObserver')
PyCore = _Class('Pyto.PyCore')
RMAppReceipt = _Class('RMAppReceipt')
RMAppReceiptIAP = _Class('RMAppReceiptIAP')
LineNumberLayoutManager = _Class('LineNumberLayoutManager')
BSXPCServiceConnectionProxy<PSPointerDefaultServiceClientToServerInterface> = _Class('BSXPCServiceConnectionProxy<PSPointerDefaultServiceClientToServerInterface>')
BSXPCServiceConnectionProxy<UISApplicationSupportXPCServerInterface> = _Class('BSXPCServiceConnectionProxy<UISApplicationSupportXPCServerInterface>')
BSXPCServiceConnectionProxy<FBSWorkspaceServiceClientInterface> = _Class('BSXPCServiceConnectionProxy<FBSWorkspaceServiceClientInterface>')
NSKVONotifying_CALayer = _Class('NSKVONotifying_CALayer')
NSKVONotifying_NSUserDefaults = _Class('NSKVONotifying_NSUserDefaults')
Python = _Class('Pyto.Python')
SceneDelegate = _Class('Pyto.SceneDelegate')
LineNumberTextViewWrapper = _Class('LineNumberTextViewWrapper')
LoadingPythonView = _Class('Pyto.LoadingPythonView')
ReplaceView = _Class('Pyto.ReplaceView')
NSKVONotifying__UISplitViewControllerPanelImplView = _Class('NSKVONotifying__UISplitViewControllerPanelImplView')
InnerTextView = _Class('NSKVONotifying_SavannaKit.InnerTextView')
ConsoleTextView = _Class('Pyto.ConsoleTextView')
LineNumberTextView = _Class('LineNumberTextView')
EditorTextView = _Class('Pyto.EditorTextView')
EditorTextView = _Class('NSKVONotifying_Pyto.EditorTextView')
HeaderLabel = _Class('Pyto.HeaderLabel')
MarqueeLabel = _Class('MarqueeLabel.MarqueeLabel')
NSKVONotifying_UITextField = _Class('NSKVONotifying_UITextField')
AppDelegate = _Class('Pyto.AppDelegate')
WidgetSimulatorViewController = _Class('Pyto.WidgetSimulatorViewController')
MarkdownPreviewController = _Class('Pyto.MarkdownPreviewController')
ActivityViewController = _Class('Pyto.ActivityViewController')
ScriptSettingsViewController = _Class('Pyto.ScriptSettingsViewController')
ContainerViewController = _Class('Pyto.ContainerViewController')
DocumentationViewController = _Class('Pyto.DocumentationViewController')
AcknowledgmentsViewController = _Class('Pyto.AcknowledgmentsViewController')
EditorViewController = _Class('Pyto.EditorViewController')
EditorSplitViewController = _Class('Pyto.EditorSplitViewController')
PipInstallerViewController = _Class('Pyto.PipInstallerViewController')
RunModuleViewController = _Class('Pyto.RunModuleViewController')
REPLViewController = _Class('Pyto.REPLViewController')
ThemableNavigationController = _Class('Pyto.ThemableNavigationController')
ConsoleViewController = _Class('Pyto.ConsoleViewController')
WatchInputSuggestionsTableViewController = _Class('Pyto.WatchInputSuggestionsTableViewController')
TemplateChooserTableViewController = _Class('Pyto.TemplateChooserTableViewController')
ThemeChooserTableViewController = _Class('Pyto.ThemeChooserTableViewController')
FileBrowserViewController = _Class('Pyto.FileBrowserViewController')
EditorActionsTableViewController = _Class('Pyto.EditorActionsTableViewController')
ResolveConflictsTableViewController = _Class('Pyto.ResolveConflictsTableViewController')
CustomIconTableViewController = _Class('Pyto.CustomIconTableViewController')
ProjectsBrowserViewController = _Class('Pyto.ProjectsBrowserViewController')
ThemeMakerTableViewController = _Class('Pyto.ThemeMakerTableViewController')
AboutTableViewController = _Class('Pyto.AboutTableViewController')
ModulesTableViewController = _Class('Pyto.ModulesTableViewController')
PipViewController = _Class('Pyto.PipViewController')
MenuTableViewController = _Class('Pyto.MenuTableViewController')
FoldersBrowserViewController = _Class('Pyto.FoldersBrowserViewController')
DocumentBrowserViewController = _Class('Pyto.DocumentBrowserViewController')
