
'''
Classes from the 'CFNetwork' framework.
'''
    
try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None
        
def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None
    
    
NSURLSessionTaskTransactionMetrics = _Class('NSURLSessionTaskTransactionMetrics')
NSURLSessionTaskMetrics = _Class('NSURLSessionTaskMetrics')
NSURLSessionWebSocketMessage = _Class('NSURLSessionWebSocketMessage')
NSURLSessionTaskHTTPAuthenticator = _Class('NSURLSessionTaskHTTPAuthenticator')
NSURLSessionTaskLocalHTTPAuthenticator = _Class('NSURLSessionTaskLocalHTTPAuthenticator')
NSURLSessionTaskBackgroundHTTPAuthenticator = _Class('NSURLSessionTaskBackgroundHTTPAuthenticator')
NSGZipDecoder = _Class('NSGZipDecoder')
NSURLDownloadInternal = _Class('NSURLDownloadInternal')
NSMemoryHTTPCookie2Storage = _Class('NSMemoryHTTPCookie2Storage')
NSURLConnectionInternal = _Class('NSURLConnectionInternal')
NSURLConnectionInternalConnection = _Class('NSURLConnectionInternalConnection')
NSURLConnectionInternalBackgroundDownload = _Class('NSURLConnectionInternalBackgroundDownload')
NSAsyncSSDownloadManager = _Class('NSAsyncSSDownloadManager')
NSHTTPCookie2Storage = _Class('NSHTTPCookie2Storage')
CFNetworkTimer = _Class('CFNetworkTimer')
NSURLSessionTaskDependency = _Class('NSURLSessionTaskDependency')
NSURLSessionTaskDependencyTree = _Class('NSURLSessionTaskDependencyTree')
NSURLSessionTaskDependencyDescription = _Class('NSURLSessionTaskDependencyDescription')
NWStreamPair = _Class('NWStreamPair')
NSNetServiceBrowser = _Class('NSNetServiceBrowser')
NSNetService = _Class('NSNetService')
NSProxyConnection = _Class('NSProxyConnection')
NSProxyConnectionStreamTask = _Class('NSProxyConnectionStreamTask')
NSPersistentHTTPCookie2Storage = _Class('NSPersistentHTTPCookie2Storage')
NSHTTPURLRequestParameters = _Class('NSHTTPURLRequestParameters')
PACURLSessionDelegate = _Class('PACURLSessionDelegate')
NSHTTPCookie = _Class('NSHTTPCookie')
NSHTTPCookieInternal = _Class('NSHTTPCookieInternal')
NSHTTPCookieInternal_Ref = _Class('NSHTTPCookieInternal_Ref')
NSHTTPCookieInternal_Data = _Class('NSHTTPCookieInternal_Data')
NSHost = _Class('NSHost')
NSHTTPCookie2StorageFilter = _Class('NSHTTPCookie2StorageFilter')
NSHTTPCookie2LookupFilter = _Class('NSHTTPCookie2LookupFilter')
NSURLProtocolInternal = _Class('NSURLProtocolInternal')
NSHTTPCookie2 = _Class('NSHTTPCookie2')
NSMutableHTTPCookie2 = _Class('NSMutableHTTPCookie2')
NSURLCredential = _Class('NSURLCredential')
NSHTTPCookie2Key = _Class('NSHTTPCookie2Key')
NSHTTPCookieStorageUtils = _Class('NSHTTPCookieStorageUtils')
NSNetServicesInternal = _Class('NSNetServicesInternal')
AuthBrokerAgentXPCListenerDelegate = _Class('AuthBrokerAgentXPCListenerDelegate')
ABRequestHandler = _Class('ABRequestHandler')
NSURLDownload = _Class('NSURLDownload')
NSURLAuthenticationChallengeInternal = _Class('NSURLAuthenticationChallengeInternal')
NSURLProtectionSpace = _Class('NSURLProtectionSpace')
NSURLAuthenticationChallenge = _Class('NSURLAuthenticationChallenge')
NSHTTPCookieStorageInternal = _Class('NSHTTPCookieStorageInternal')
NSHTTPCookieStorage = _Class('NSHTTPCookieStorage')
NSHTTPCookieStorageToCookie2Storage = _Class('NSHTTPCookieStorageToCookie2Storage')
NSURLCredentialStorage = _Class('NSURLCredentialStorage')
NSHTTPURLResponseInternal = _Class('NSHTTPURLResponseInternal')
NSCachedURLResponseInternal = _Class('NSCachedURLResponseInternal')
NSCachedURLResponse = _Class('NSCachedURLResponse')
NSURLResponse = _Class('NSURLResponse')
NSHTTPURLResponse = _Class('NSHTTPURLResponse')
NSURLResponseInternal = _Class('NSURLResponseInternal')
NSURLStorageURLCacheDB = _Class('NSURLStorageURLCacheDB')
NSURLCacheInternal = _Class('NSURLCacheInternal')
NSURLCache = _Class('NSURLCache')
CONNECTION_SessionTask = _Class('CONNECTION_SessionTask')
NSURLConnection = _Class('NSURLConnection')
NSURLSessionEffectiveConfiguration = _Class('NSURLSessionEffectiveConfiguration')
NSURLSessionMutableEffectiveConfiguration = _Class('NSURLSessionMutableEffectiveConfiguration')
NSURLSessionTask = _Class('NSURLSessionTask')
NSURLSessionStreamTask = _Class('NSURLSessionStreamTask')
NSURLSessionDataTask = _Class('NSURLSessionDataTask')
NSURLSessionUploadTask = _Class('NSURLSessionUploadTask')
NSURLSessionAVAggregateAssetDownloadTask = _Class('NSURLSessionAVAggregateAssetDownloadTask')
NSURLSessionAVAssetDownloadTask = _Class('NSURLSessionAVAssetDownloadTask')
AVAssetDownloadTask = _Class('AVAssetDownloadTask')
NSURLSessionWebSocketTask = _Class('NSURLSessionWebSocketTask')
NSURLSessionDownloadTask = _Class('NSURLSessionDownloadTask')
NSURLRequestInternal = _Class('NSURLRequestInternal')
NSURLRequest = _Class('NSURLRequest')
NSMutableURLRequest = _Class('NSMutableURLRequest')
NSURLProtocol = _Class('NSURLProtocol')
NSAboutURLProtocol = _Class('NSAboutURLProtocol')
NSURLSessionConfiguration = _Class('NSURLSessionConfiguration')
NSURLSession = _Class('NSURLSession')
AVAssetDownloadURLSession = _Class('AVAssetDownloadURLSession')