
'''
Classes from the 'ContactsUICore' framework.
'''
    
try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None
        
def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None
    
    
CNMCProfileConnection = _Class('CNMCProfileConnection')
CNUIDefaultUserActionFetcher = _Class('CNUIDefaultUserActionFetcher')
CNUICoreFamilyMemberContactItem = _Class('CNUICoreFamilyMemberContactItem')
CNUIUserActionItemComparator = _Class('CNUIUserActionItemComparator')
CNUIUserActionRanking = _Class('CNUIUserActionRanking')
CNUIImageProvider = _Class('CNUIImageProvider')
CNUICoreProposedContactsFetchingDecorator = _Class('CNUICoreProposedContactsFetchingDecorator')
CNUIPlaceholderProviderFactory = _Class('CNUIPlaceholderProviderFactory')
CNUIUserActionItemList = _Class('CNUIUserActionItemList')
CNUIPRLikenessPhotoProvider = _Class('CNUIPRLikenessPhotoProvider')
CNHandle = _Class('CNHandle')
CNUIPRLikenessProvider = _Class('CNUIPRLikenessProvider')
CNUICoreContactNoteValueFilter = _Class('CNUICoreContactNoteValueFilter')
CNUIAvatarLayoutManager = _Class('CNUIAvatarLayoutManager')
CNUIAvatarLayoutLayerItem = _Class('CNUIAvatarLayoutLayerItem')
CNUIAvatarLayoutItemConfiguration = _Class('CNUIAvatarLayoutItemConfiguration')
CNUICoreFamilyInfo = _Class('CNUICoreFamilyInfo')
CNUIIDSIDQueryControllerWrapper = _Class('CNUIIDSIDQueryControllerWrapper')
CNUICoreContactPhotoValueFilter = _Class('CNUICoreContactPhotoValueFilter')
CNUICoreContactManagementConsentInspector = _Class('CNUICoreContactManagementConsentInspector')
CNUICoreMainWhitelistedContactsController = _Class('CNUICoreMainWhitelistedContactsController')
CNUIApplicationLaunchOptions = _Class('CNUIApplicationLaunchOptions')
CNTUCallProvider = _Class('CNTUCallProvider')
CNUICoreEditAuthorizationCheck = _Class('CNUICoreEditAuthorizationCheck')
CNUICoreContactNicknameValueFilter = _Class('CNUICoreContactNicknameValueFilter')
CNUIUserActionTargetDiscovering = _Class('CNUIUserActionTargetDiscovering')
CNUIUserActionTargetDiscoveringReplaySubjectPair = _Class('CNUIUserActionTargetDiscoveringReplaySubjectPair')
CNUIPRLikenessLoadingPlaceholderProvider = _Class('CNUIPRLikenessLoadingPlaceholderProvider')
CNUIPRLikenessLoadingGroupPlaceholderProvider = _Class('CNUIPRLikenessLoadingGroupPlaceholderProvider')
CNUIUserActionDisambiguationModeler = _Class('CNUIUserActionDisambiguationModeler')
CNUIUserActionTargetDiscoveringReplaySubject = _Class('CNUIUserActionTargetDiscoveringReplaySubject')
CNFirstRawActionsModelReplaySubject = _Class('CNFirstRawActionsModelReplaySubject')
CNDiscoveredUserActionReplaySubject = _Class('CNDiscoveredUserActionReplaySubject')
CNUICoreContactTypeAssessor = _Class('CNUICoreContactTypeAssessor')
CNUICoreScreentimePasscodeInspector = _Class('CNUICoreScreentimePasscodeInspector')
CNUIContactPropertyRanker = _Class('CNUIContactPropertyRanker')
CNUICoreFamilyMemberContactsController = _Class('CNUICoreFamilyMemberContactsController')
CNUIUserActionWorkspaceURLOpener = _Class('CNUIUserActionWorkspaceURLOpener')
CNUIUserActionListModel = _Class('CNUIUserActionListModel')
CNTUCallProviderManagerDelegate = _Class('CNTUCallProviderManagerDelegate')
CNLSApplicationWorkspace = _Class('CNLSApplicationWorkspace')
CNUICoreFamilyElement = _Class('CNUICoreFamilyElement')
CNUIPRLikenessPlaceholderProvider = _Class('CNUIPRLikenessPlaceholderProvider')
CNUIPRLikenessLookup = _Class('CNUIPRLikenessLookup')
CNTUCallProviderManager = _Class('CNTUCallProviderManager')
CNUIUserActionTargetDiscoveringObservableCancelationToken = _Class('CNUIUserActionTargetDiscoveringObservableCancelationToken')
CNCallProvidersChangedCancelationToken = _Class('CNCallProvidersChangedCancelationToken')
CNUICoreLogProvider = _Class('CNUICoreLogProvider')
CNUIInteractionDonor = _Class('CNUIInteractionDonor')
CNUICoreContactPropertyFilterBuilder = _Class('CNUICoreContactPropertyFilterBuilder')
CNUICoreContactStoreProductionFacade = _Class('CNUICoreContactStoreProductionFacade')
CNUICoreContactStoreTestFacade = _Class('CNUICoreContactStoreTestFacade')
CNUICoreContactRelationshipsFilter = _Class('CNUICoreContactRelationshipsFilter')
CNUIUserActionExtensionURLOpener = _Class('CNUIUserActionExtensionURLOpener')
CNUICoreFamilyInfoRetriever = _Class('CNUICoreFamilyInfoRetriever')
CNUIDefaultUserActionRecorder = _Class('CNUIDefaultUserActionRecorder')
CNUIIDSContactPropertyResolver = _Class('CNUIIDSContactPropertyResolver')
CNUIIDSAvailabilityProvider = _Class('CNUIIDSAvailabilityProvider')
CNUIDSHandleAvailabilityPromise = _Class('CNUIDSHandleAvailabilityPromise')
CNUIDHandleAvailabilityFuture = _Class('CNUIDHandleAvailabilityFuture')
CNUIUserActionDiscoveringEnvironment = _Class('CNUIUserActionDiscoveringEnvironment')
CNUILikenessRenderer = _Class('CNUILikenessRenderer')
CNCapabilities = _Class('CNCapabilities')
CNUICoreContactEditingSession = _Class('CNUICoreContactEditingSession')
CNUICoreFamilyMemberContactsModel = _Class('CNUICoreFamilyMemberContactsModel')
CNUICoreFamilyMemberContactsStore = _Class('CNUICoreFamilyMemberContactsStore')
CNUICoreFamilyMemberWhitelistedContactsController = _Class('CNUICoreFamilyMemberWhitelistedContactsController')
CNUICoreContactPropertyValueFilterFactory = _Class('CNUICoreContactPropertyValueFilterFactory')
CNUIUserActivityManager = _Class('CNUIUserActivityManager')
CNUIRemotePhotoFutures = _Class('CNUIRemotePhotoFutures')
CNUIUserActionListDataSource = _Class('CNUIUserActionListDataSource')
CNUIUserActionDisambiguationViewDataSource = _Class('CNUIUserActionDisambiguationViewDataSource')
CNUIUserActionTargetDiscoveryCache = _Class('CNUIUserActionTargetDiscoveryCache')
CNUIDSHandleAvailabilityCache = _Class('CNUIDSHandleAvailabilityCache')
CNUIDSIMessageHandleAvailabilityCache = _Class('CNUIDSIMessageHandleAvailabilityCache')
CNUIDSFaceTimeHandleAvailabilityCache = _Class('CNUIDSFaceTimeHandleAvailabilityCache')
CNUIUserActionListModelCache = _Class('CNUIUserActionListModelCache')
CNUICoreContactsSyncProductionTrigger = _Class('CNUICoreContactsSyncProductionTrigger')
CNUIContactPropertyIDSHandle = _Class('CNUIContactPropertyIDSHandle')
CNUICoreRecentsManager = _Class('CNUICoreRecentsManager')
CNUIPRLikenessResolver = _Class('CNUIPRLikenessResolver')
CNUIPRLikenessResolverOptions = _Class('CNUIPRLikenessResolverOptions')
CNUICoreContactFetchRequestAccumulator = _Class('CNUICoreContactFetchRequestAccumulator')
CNUIMeContactComparisonStrategyUnified = _Class('CNUIMeContactComparisonStrategyUnified')
CNUIMeContactComparisonStrategyIdentifier = _Class('CNUIMeContactComparisonStrategyIdentifier')
CNUIMeContactMonitor = _Class('CNUIMeContactMonitor')
CNUICoreContactScratchpad = _Class('CNUICoreContactScratchpad')
CNUIPassKitWrapper = _Class('CNUIPassKitWrapper')
CNUICoreWhitelistedContactsControllerOptions = _Class('CNUICoreWhitelistedContactsControllerOptions')
CNUIUserActivityRestorer = _Class('CNUIUserActivityRestorer')
CNUISnowglobeUtilities = _Class('CNUISnowglobeUtilities')
CNUIRenderedLikenessCacheEntry = _Class('CNUIRenderedLikenessCacheEntry')
CNUIUserActionDisambiguationModelFinalizer = _Class('CNUIUserActionDisambiguationModelFinalizer')
CNUICoreFamilyMemberSaveRequestFactory = _Class('CNUICoreFamilyMemberSaveRequestFactory')
CNUIDowntimeLogger = _Class('CNUIDowntimeLogger')
CNUICoreFamilyMemberContactsModelRetriever = _Class('CNUICoreFamilyMemberContactsModelRetriever')
CNUICoreContactEdit = _Class('CNUICoreContactEdit')
CNUICoreContactMatcher = _Class('CNUICoreContactMatcher')
CNUIUserActionItem = _Class('CNUIUserActionItem')
CNUICoreFamilyMemberContactsModelBuilder = _Class('CNUICoreFamilyMemberContactsModelBuilder')
CNUICoreInMemoryWhitelistedContactsDataSourceDecorator = _Class('CNUICoreInMemoryWhitelistedContactsDataSourceDecorator')
CNUILibraryFolderDiscovery = _Class('CNUILibraryFolderDiscovery')
CNUICoreContactRefetcher = _Class('CNUICoreContactRefetcher')
CNUILikenessRenderingScope = _Class('CNUILikenessRenderingScope')
CNUIUserActionCacheKeyGenerator = _Class('CNUIUserActionCacheKeyGenerator')
CNUILikenessFingerprint = _Class('CNUILikenessFingerprint')
CNUIUserActionContext = _Class('CNUIUserActionContext')
CNUIUserActionTarget = _Class('CNUIUserActionTarget')
TestCNUIIDSHandleAvailability = _Class('TestCNUIIDSHandleAvailability')
CNUIRTTUtilities = _Class('CNUIRTTUtilities')
CNContactsUIError = _Class('CNContactsUIError')
CNUIIDSRequest = _Class('CNUIIDSRequest')
CNUICoreContactAggregateValueFilter = _Class('CNUICoreContactAggregateValueFilter')
CNUICreateContactIntentResponse = _Class('CNUICreateContactIntentResponse')
CNUICreateContactIntent = _Class('CNUICreateContactIntent')