
'''
Classes from the 'IDS' framework.
'''
    
try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None
        
def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None
    
    
IDSTransactionLogTaskHandler = _Class('IDSTransactionLogTaskHandler')
IDSTransactionLogSyncTaskHandler = _Class('IDSTransactionLogSyncTaskHandler')
IDSTransactionLogBaseTaskHandler = _Class('IDSTransactionLogBaseTaskHandler')
IDSTransactionLogTaskHandlerAccountInfo = _Class('IDSTransactionLogTaskHandlerAccountInfo')
IDSServiceMonitor = _Class('IDSServiceMonitor')
IDSRealTimeEncryptionProxy = _Class('IDSRealTimeEncryptionProxy')
IDSInternalQueueController = _Class('IDSInternalQueueController')
IDSGroupContextDataSource = _Class('IDSGroupContextDataSource')
IDSIDQueryController = _Class('IDSIDQueryController')
IDSXPCActivityMonitorInterface = _Class('IDSXPCActivityMonitorInterface')
IDSDeviceConnection = _Class('IDSDeviceConnection')
IDSDatagramChannel = _Class('IDSDatagramChannel')
IDSDataChannelLinkContext = _Class('IDSDataChannelLinkContext')
IDSDevice = _Class('IDSDevice')
IDSXPCOpportunisticInterface = _Class('IDSXPCOpportunisticInterface')
IDSXPCConnectionTimeoutProxy = _Class('IDSXPCConnectionTimeoutProxy')
IDSXPCConnection = _Class('IDSXPCConnection')
IDSLogging = _Class('IDSLogging')
IDSTransportLog = _Class('IDSTransportLog')
IDSPhoneSubscriptionSelector = _Class('IDSPhoneSubscriptionSelector')
IDSPhoneTemporaryAliasDescription = _Class('IDSPhoneTemporaryAliasDescription')
IDSPhoneSubscription = _Class('IDSPhoneSubscription')
IDSTransactionLogMessage = _Class('IDSTransactionLogMessage')
IDSTransactionLogDictionaryMessage = _Class('IDSTransactionLogDictionaryMessage')
IDSTransactionLogDataMessage = _Class('IDSTransactionLogDataMessage')
IDSAutoCleanup = _Class('IDSAutoCleanup')
IDSDaemonRequestTimer = _Class('IDSDaemonRequestTimer')
IDSDaemonRequestContext = _Class('IDSDaemonRequestContext')
IDSService = _Class('IDSService')
IDSXPCPairedDeviceManagerInterface = _Class('IDSXPCPairedDeviceManagerInterface')
IDSReportiMessageSpamDaemonResponseListener = _Class('IDSReportiMessageSpamDaemonResponseListener')
IDSHomeKitManager = _Class('IDSHomeKitManager')
IDSAccount = _Class('IDSAccount')
IDSLocalPairingRecord = _Class('IDSLocalPairingRecord')
IDSLocalPairingLocalDeviceRecord = _Class('IDSLocalPairingLocalDeviceRecord')
IDSLocalPairingPairedDeviceRecord = _Class('IDSLocalPairingPairedDeviceRecord')
IDSLocalPairingIdentityDataErrorPair = _Class('IDSLocalPairingIdentityDataErrorPair')
IDSXPCDaemonController = _Class('IDSXPCDaemonController')
IDSLocalPairingAddPairedDeviceInfo = _Class('IDSLocalPairingAddPairedDeviceInfo')
IDSQuickSwitchAcknowledgementTracker = _Class('IDSQuickSwitchAcknowledgementTracker')
IDSDaemonProtocolController = _Class('IDSDaemonProtocolController')
IDSQuickRelayFixedTokenAllocator = _Class('IDSQuickRelayFixedTokenAllocator')
IDSGroupContextControllerContent = _Class('IDSGroupContextControllerContent')
IDSGroupContextController = _Class('IDSGroupContextController')
IDSAccountController = _Class('IDSAccountController')
IDSXPCConnectionRemoteObjectPromise = _Class('IDSXPCConnectionRemoteObjectPromise')
IDSRegistrationControlDaemonResponseListener = _Class('IDSRegistrationControlDaemonResponseListener')
IDSPhoneCertificateVendor = _Class('IDSPhoneCertificateVendor')
IDSAuthenticationSigningResult = _Class('IDSAuthenticationSigningResult')
IDSAuthenticationCertificateSignature = _Class('IDSAuthenticationCertificateSignature')
IDSCarrierToken = _Class('IDSCarrierToken')
IDSCarrierTokenRequestParameters = _Class('IDSCarrierTokenRequestParameters')
IDSPairedDeviceManager = _Class('IDSPairedDeviceManager')
IDSXPCDaemonClientInterface = _Class('IDSXPCDaemonClientInterface')
IDSXPCDaemonInterface = _Class('IDSXPCDaemonInterface')
IDSGroupSessionUnicastParameter = _Class('IDSGroupSessionUnicastParameter')
IDSTransactionLogTask = _Class('IDSTransactionLogTask')
IDSTransactionLogSyncTask = _Class('IDSTransactionLogSyncTask')
IDSDaemonResponseHandler = _Class('IDSDaemonResponseHandler')
IDSXPCPairingInterface = _Class('IDSXPCPairingInterface')
IDSConnection = _Class('IDSConnection')
IDSBatchIDQueryController = _Class('IDSBatchIDQueryController')
IDSAppleCareDaemonResponseListener = _Class('IDSAppleCareDaemonResponseListener')
IDSSession = _Class('IDSSession')
IDSSignInController = _Class('IDSSignInController')
IDSSignInControllerAccountDescription = _Class('IDSSignInControllerAccountDescription')
IDSSignInServiceUserStatus = _Class('IDSSignInServiceUserStatus')
IDSSignInServiceUserInfo = _Class('IDSSignInServiceUserInfo')
IDSGroupContextNotifyingObserver = _Class('IDSGroupContextNotifyingObserver')
IDSActivityMonitor = _Class('IDSActivityMonitor')
IDSActivityUpdate = _Class('IDSActivityUpdate')
IDSActivityInfo = _Class('IDSActivityInfo')
IDSDaemonListener = _Class('IDSDaemonListener')
IDSServiceContainer = _Class('IDSServiceContainer')
IDSServiceAvailabilityController = _Class('IDSServiceAvailabilityController')
IDSXPCRegistrationInterface = _Class('IDSXPCRegistrationInterface')
IDSGroupSession = _Class('IDSGroupSession')
IDSXPCReunionSyncInterface = _Class('IDSXPCReunionSyncInterface')
IDSXPCInternalTestingInterface = _Class('IDSXPCInternalTestingInterface')
IDSDaemonController = _Class('IDSDaemonController')
IDSContinuity = _Class('IDSContinuity')
IDSDaemonControllerForwarder = _Class('IDSDaemonControllerForwarder')