
'''
Classes from the 'MapsSync' framework.
'''
    
try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None
        
def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None
    
    
MapsSync.MapsSyncEventDebouncer = _Class('MapsSync.MapsSyncEventDebouncer')
MapsSync.MapsSyncWrapperFactory = _Class('MapsSync.MapsSyncWrapperFactory')
MapsSync.MapsSyncDataBase_0_0_1 = _Class('MapsSync.MapsSyncDataBase_0_0_1')
MapsSync.MapsSyncDataBase_initial = _Class('MapsSync.MapsSyncDataBase_initial')
MapsSync.MapsSyncGeo = _Class('MapsSync.MapsSyncGeo')
MapsSync.MapsSyncPredicate = _Class('MapsSync.MapsSyncPredicate')
MapsSync.MapsSyncDataContainerXPCDelegate = _Class('MapsSync.MapsSyncDataContainerXPCDelegate')
MapsSync.MapsSyncXPCServer = _Class('MapsSync.MapsSyncXPCServer')
MapsSync.MapsSyncDataContainer = _Class('MapsSync.MapsSyncDataContainer')
MapsSync.MapsSyncXPCDataContainer = _Class('MapsSync.MapsSyncXPCDataContainer')
MapsSync.MapsSyncCloudKitDataContainer = _Class('MapsSync.MapsSyncCloudKitDataContainer')
MapsSync.MapsSyncMemoryOnlyDataContainer = _Class('MapsSync.MapsSyncMemoryOnlyDataContainer')
MapsSync.MapsSyncUtil = _Class('MapsSync.MapsSyncUtil')
MapsSync.MapsSyncBatch = _Class('MapsSync.MapsSyncBatch')
MapsSync.MapsSyncFetchedResultsControllerDelegate = _Class('MapsSync.MapsSyncFetchedResultsControllerDelegate')
MapsSync.MapsSyncDataSession = _Class('MapsSync.MapsSyncDataSession')
MapsSync.MapsSyncDataValidator = _Class('MapsSync.MapsSyncDataValidator')
MapsSync.MapsSyncBaseQuery = _Class('MapsSync.MapsSyncBaseQuery')
MapsSync.MapsSyncVehicleQuery = _Class('MapsSync.MapsSyncVehicleQuery')
MapsSync.MapsSyncCuratedCollectionQuery = _Class('MapsSync.MapsSyncCuratedCollectionQuery')
MapsSync.MapsSyncCollectionItemQuery = _Class('MapsSync.MapsSyncCollectionItemQuery')
MapsSync.MapsSyncFavoriteItemQuery = _Class('MapsSync.MapsSyncFavoriteItemQuery')
MapsSync.MapsSyncCollectionPlaceItemQuery = _Class('MapsSync.MapsSyncCollectionPlaceItemQuery')
MapsSync.MapsSyncCollectionTransitItemQuery = _Class('MapsSync.MapsSyncCollectionTransitItemQuery')
MapsSync.MapsSyncDataQuery = _Class('MapsSync.MapsSyncDataQuery')
MapsSync.MapsSyncCollectionQuery = _Class('MapsSync.MapsSyncCollectionQuery')
MapsSync.MapsSyncHistoryItemQuery = _Class('MapsSync.MapsSyncHistoryItemQuery')
MapsSync.MapsSyncMutableBaseItem = _Class('MapsSync.MapsSyncMutableBaseItem')
MapsSync.MapsSyncMutableReviewedPlace = _Class('MapsSync.MapsSyncMutableReviewedPlace')
MapsSync.MapsSyncMutableFavoriteItem = _Class('MapsSync.MapsSyncMutableFavoriteItem')
MapsSync.MapsSyncMutableAnonymousCredential = _Class('MapsSync.MapsSyncMutableAnonymousCredential')
MapsSync.MapsSyncMutableVehicle = _Class('MapsSync.MapsSyncMutableVehicle')
MapsSync.MapsSyncMutableCollection = _Class('MapsSync.MapsSyncMutableCollection')
MapsSync.MapsSyncMutableCuratedCollection = _Class('MapsSync.MapsSyncMutableCuratedCollection')
MapsSync.MapsSyncMutableHistoryItem = _Class('MapsSync.MapsSyncMutableHistoryItem')
MapsSync.MapsSyncMutableHistoryRideShareItem = _Class('MapsSync.MapsSyncMutableHistoryRideShareItem')
MapsSync.MapsSyncMutableHistorySearchItem = _Class('MapsSync.MapsSyncMutableHistorySearchItem')
MapsSync.MapsSyncMutableHistoryPlaceItem = _Class('MapsSync.MapsSyncMutableHistoryPlaceItem')
MapsSync.MapsSyncMutableHistoryTransitItem = _Class('MapsSync.MapsSyncMutableHistoryTransitItem')
MapsSync.MapsSyncMutableHistoryDirectionsItem = _Class('MapsSync.MapsSyncMutableHistoryDirectionsItem')
MapsSync.MapsSyncMutableHistoryEvDirectionsItem = _Class('MapsSync.MapsSyncMutableHistoryEvDirectionsItem')
MapsSync.MapsSyncMutableCachedCuratedCollection = _Class('MapsSync.MapsSyncMutableCachedCuratedCollection')
MapsSync.MapsSyncMutableCachedUserReview = _Class('MapsSync.MapsSyncMutableCachedUserReview')
MapsSync.MapsSyncMutableCollectionItem = _Class('MapsSync.MapsSyncMutableCollectionItem')
MapsSync.MapsSyncMutableCollectionTransitItem = _Class('MapsSync.MapsSyncMutableCollectionTransitItem')
MapsSync.MapsSyncMutableCollectionPlaceItem = _Class('MapsSync.MapsSyncMutableCollectionPlaceItem')
MapsSync.MapsSyncObjectWrapper = _Class('MapsSync.MapsSyncObjectWrapper')
MapsSync.MapsSyncBaseItem = _Class('MapsSync.MapsSyncBaseItem')
MapsSync.MapsSyncReviewedPlace = _Class('MapsSync.MapsSyncReviewedPlace')
MapsSync.MapsSyncFavoriteItem = _Class('MapsSync.MapsSyncFavoriteItem')
MapsSync.MapsSyncAnonymousCredential = _Class('MapsSync.MapsSyncAnonymousCredential')
MapsSync.MapsSyncVehicle = _Class('MapsSync.MapsSyncVehicle')
MapsSync.MapsSyncCollection = _Class('MapsSync.MapsSyncCollection')
MapsSync.MapsSyncCuratedCollection = _Class('MapsSync.MapsSyncCuratedCollection')
MapsSync.MapsSyncHistoryItem = _Class('MapsSync.MapsSyncHistoryItem')
MapsSync.MapsSyncHistoryRideShareItem = _Class('MapsSync.MapsSyncHistoryRideShareItem')
MapsSync.MapsSyncHistorySearchItem = _Class('MapsSync.MapsSyncHistorySearchItem')
MapsSync.MapsSyncHistoryPlaceItem = _Class('MapsSync.MapsSyncHistoryPlaceItem')
MapsSync.MapsSyncHistoryTransitItem = _Class('MapsSync.MapsSyncHistoryTransitItem')
MapsSync.MapsSyncHistoryDirectionsItem = _Class('MapsSync.MapsSyncHistoryDirectionsItem')
MapsSync.MapsSyncHistoryEvDirectionsItem = _Class('MapsSync.MapsSyncHistoryEvDirectionsItem')
MapsSync.MapsSyncCachedCuratedCollection = _Class('MapsSync.MapsSyncCachedCuratedCollection')
MapsSync.MapsSyncCachedUserReview = _Class('MapsSync.MapsSyncCachedUserReview')
MapsSync.MapsSyncCollectionItem = _Class('MapsSync.MapsSyncCollectionItem')
MapsSync.MapsSyncCollectionTransitItem = _Class('MapsSync.MapsSyncCollectionTransitItem')
MapsSync.MapsSyncCollectionPlaceItem = _Class('MapsSync.MapsSyncCollectionPlaceItem')
MapsSync.MapsSyncPersistentContainer = _Class('MapsSync.MapsSyncPersistentContainer')
MapsSyncManagedVehicle = _Class('MapsSyncManagedVehicle')
MapsSyncManagedCollection = _Class('MapsSyncManagedCollection')
MapsSyncManagedContactHandle = _Class('MapsSyncManagedContactHandle')
MapsSyncManagedCuratedCollection = _Class('MapsSyncManagedCuratedCollection')
MapsSyncManagedFavoriteItem = _Class('MapsSyncManagedFavoriteItem')
MapsSyncManagedHistoryItem = _Class('MapsSyncManagedHistoryItem')
MapsSyncManagedHistoryTransitItem = _Class('MapsSyncManagedHistoryTransitItem')
MapsSyncManagedHistorySearchItem = _Class('MapsSyncManagedHistorySearchItem')
MapsSyncManagedHistoryDirectionsItem = _Class('MapsSyncManagedHistoryDirectionsItem')
MapsSyncManagedHistoryEvDirectionsItem = _Class('MapsSyncManagedHistoryEvDirectionsItem')
MapsSyncManagedHistoryRideShareItem = _Class('MapsSyncManagedHistoryRideShareItem')
MapsSyncManagedHistoryPlaceItem = _Class('MapsSyncManagedHistoryPlaceItem')
MapsSyncManagedMixinMapItem = _Class('MapsSyncManagedMixinMapItem')
MapsSyncManagedCachedUserReview = _Class('MapsSyncManagedCachedUserReview')
MapsSyncManagedReviewedPlace = _Class('MapsSyncManagedReviewedPlace')
MapsSyncManagedAnonymousCredential = _Class('MapsSyncManagedAnonymousCredential')
MapsSyncManagedCachedCuratedCollection = _Class('MapsSyncManagedCachedCuratedCollection')
MapsSyncManagedCollectionItem = _Class('MapsSyncManagedCollectionItem')
MapsSyncManagedCollectionTransitItem = _Class('MapsSyncManagedCollectionTransitItem')
MapsSyncManagedCollectionPlaceItem = _Class('MapsSyncManagedCollectionPlaceItem')
MapsSync.MapsSyncError = _Class('MapsSync.MapsSyncError')