'''
Classes from the 'MessageUI' framework.
'''
    
try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None
        
def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None
    
    
MFStringAccumulator = _Class('MFStringAccumulator')
MFSpringAnimationDelegate = _Class('MFSpringAnimationDelegate')
MFSoundController = _Class('MFSoundController')
MFSimpleAnimationCoordinator = _Class('MFSimpleAnimationCoordinator')
MFSendMailIntentDonation = _Class('MFSendMailIntentDonation')
MFScannedDocumentConverter = _Class('MFScannedDocumentConverter')
MFAddressConcatenator = _Class('MFAddressConcatenator')
MFPreferencesURL = _Class('MFPreferencesURL')
MFPopupButtonItem = _Class('MFPopupButtonItem')
MFPlaceholderMessageRewriter = _Class('MFPlaceholderMessageRewriter')
MFPhotoPickerProgressItem = _Class('MFPhotoPickerProgressItem')
MFPhotoPickerProgressManager = _Class('MFPhotoPickerProgressManager')
MFMixedMessageFragment = _Class('MFMixedMessageFragment')
MFMessageBodyStringAccumulator = _Class('MFMessageBodyStringAccumulator')
MFMessageBodyElement = _Class('MFMessageBodyElement')
MFMessageBodyParserObject = _Class('MFMessageBodyParserObject')
MFMessageBodySubparser = _Class('MFMessageBodySubparser')
MFMessageBodyOriginalTextSubparser = _Class('MFMessageBodyOriginalTextSubparser')
MFMessageBodyParser = _Class('MFMessageBodyParser')
MFMessageBodyHTMLParser = _Class('MFMessageBodyHTMLParser')
MFMediaExporter = _Class('MFMediaExporter')
MFMailSignatureController = _Class('MFMailSignatureController')
MFMailPopoverManager = _Class('MFMailPopoverManager')
MFMailComposeContactsSearchController = _Class('MFMailComposeContactsSearchController')
MFMailAccountProxyGenerator = _Class('MFMailAccountProxyGenerator')
MFMailAccountProxy = _Class('MFMailAccountProxy')
MFLANHandoffAgent = _Class('MFLANHandoffAgent')
MFLANHandoffContext = _Class('MFLANHandoffContext')
MFHardwareJPEGScaler = _Class('MFHardwareJPEGScaler')
MFFontMetricCache = _Class('MFFontMetricCache')
MFFileAttachment = _Class('MFFileAttachment')
MFDropTarget = _Class('MFDropTarget')
MFDragSource = _Class('MFDragSource')
MFDataDetectors = _Class('MFDataDetectors')
MFContactsSearchResultsModel = _Class('MFContactsSearchResultsModel')
MFContactsSearchManager = _Class('MFContactsSearchManager')
MFContactsSearchTaskContext = _Class('MFContactsSearchTaskContext')
MFComposeTypeFactory = _Class('MFComposeTypeFactory')
MFComposeTextStyle = _Class('MFComposeTextStyle')
MFComposeRecipientOriginContext = _Class('MFComposeRecipientOriginContext')
MFComposeRecipients = _Class('MFComposeRecipients')
MFComposeDisplayMetrics = _Class('MFComposeDisplayMetrics')
MFComposeRecipient = _Class('MFComposeRecipient')
MFRecentComposeRecipient = _Class('MFRecentComposeRecipient')
MFComposeRecipientGroup = _Class('MFComposeRecipientGroup')
MFRecentComposeRecipientGroup = _Class('MFRecentComposeRecipientGroup')
MFCalendarComposeRecipient = _Class('MFCalendarComposeRecipient')
MFAttachmentPasteboardRepresentation = _Class('MFAttachmentPasteboardRepresentation')
MFAttachmentDragPreviewInfo = _Class('MFAttachmentDragPreviewInfo')
MFWebKitMainThread = _Class('MFWebKitMainThread')
MFAlertOverlayController = _Class('MFAlertOverlayController')
MFReformattedAddress = _Class('MFReformattedAddress')
MFAddressPickerReformatter = _Class('MFAddressPickerReformatter')
MFAddressBookManager = _Class('MFAddressBookManager')
MFPlaceholderMailDeliveryUI = _Class('MFPlaceholderMailDeliveryUI')
MFMailDropMailDeliveryUI = _Class('MFMailDropMailDeliveryUI')
MFComposeAttachmentInfo = _Class('MFComposeAttachmentInfo')
MFPersonTransformer = _Class('MFPersonTransformer')
MFMailIntentTransformer = _Class('MFMailIntentTransformer')
MFCenteredTextAttachment = _Class('MFCenteredTextAttachment')
MFBarButtonItem = _Class('MFBarButtonItem')
MFMessageURLProtocol = _Class('MFMessageURLProtocol')
MFAtomIcon = _Class('MFAtomIcon')
MFSpringAnimation = _Class('MFSpringAnimation')
MFContactsSearchOperation = _Class('MFContactsSearchOperation')
MFContactsAutocompleteSearchOperation = _Class('MFContactsAutocompleteSearchOperation')
MFComposeActivityHandoffOperation = _Class('MFComposeActivityHandoffOperation')
MFSecureMIMEPersonHeaderView = _Class('MFSecureMIMEPersonHeaderView')
MFRoundProgressView = _Class('MFRoundProgressView')
MFProgressView = _Class('MFProgressView')
MFModernLabelledAtomList = _Class('MFModernLabelledAtomList')
MFModernAtomBackgroundView = _Class('MFModernAtomBackgroundView')
MFModernAtomIconView = _Class('MFModernAtomIconView')
MFMessageContentProgressLayer = _Class('MFMessageContentProgressLayer')
MFMessageContentLoadingView = _Class('MFMessageContentLoadingView')
MFComposeHeaderView = _Class('MFComposeHeaderView')
MFComposeRecipientView = _Class('MFComposeRecipientView')
MFComposeRecipientTextView = _Class('MFComposeRecipientTextView')
MFComposeDropPreviewView = _Class('MFComposeDropPreviewView')
MFAttachmentImageGenerator = _Class('MFAttachmentImageGenerator')
MFComposeWebView = _Class('MFComposeWebView')
MFMailComposeNavigationBarTitleView = _Class('MFMailComposeNavigationBarTitleView')
MFComposeActionCardTitleView = _Class('MFComposeActionCardTitleView')
MFMailComposeHeaderView = _Class('MFMailComposeHeaderView')
MFComposeWebContentVariationView = _Class('MFComposeWebContentVariationView')
MFComposeSubjectView = _Class('MFComposeSubjectView')
MFComposeMultiView = _Class('MFComposeMultiView')
MFComposeImageSizeView = _Class('MFComposeImageSizeView')
MFComposeFromView = _Class('MFComposeFromView')
MFMailComposeRecipientTextView = _Class('MFMailComposeRecipientTextView')
MFMailComposeToField = _Class('MFMailComposeToField')
MFModernAtomView = _Class('MFModernAtomView')
MFModernComposeRecipientAtom = _Class('MFModernComposeRecipientAtom')
MFCorecipientsIndicatorAtom = _Class('MFCorecipientsIndicatorAtom')
MFRecipientTableViewCell = _Class('MFRecipientTableViewCell')
MFPhotoPickerSectionHeaderView = _Class('MFPhotoPickerSectionHeaderView')
MFPhotoPickerCell = _Class('MFPhotoPickerCell')
MFRoundedCornersStackView = _Class('MFRoundedCornersStackView')
MFMailComposeView = _Class('MFMailComposeView')
MFComposeScrollView = _Class('MFComposeScrollView')
MFComposeSubjectTextView = _Class('MFComposeSubjectTextView')
MFHeaderLabelView = _Class('MFHeaderLabelView')
MFCaptionLabel = _Class('MFCaptionLabel')
MFPopupButton = _Class('MFPopupButton')
MFModernAddressAtom = _Class('MFModernAddressAtom')
MFAtomTextView = _Class('MFAtomTextView')
MFDimmableButton = _Class('MFDimmableButton')
MFConfirmationButton = _Class('MFConfirmationButton')
MFComposeTextColorButton = _Class('MFComposeTextColorButton')
MFComposeSMIMELockButton = _Class('MFComposeSMIMELockButton')
MFComposeSendAccessoryButton = _Class('MFComposeSendAccessoryButton')
MFComposeStyleSelectorButton = _Class('MFComposeStyleSelectorButton')
MFComposeFontSelectorButton = _Class('MFComposeFontSelectorButton')
MFSearchShadowView = _Class('MFSearchShadowView')
MFMailComposePlaceholderViewController = _Class('MFMailComposePlaceholderViewController')
MFMailComposeInternalViewController = _Class('MFMailComposeInternalViewController')
MFMailComposeController = _Class('MFMailComposeController')
MFComposeStyleSelectorViewController = _Class('MFComposeStyleSelectorViewController')
MFComposeColorPickerController = _Class('MFComposeColorPickerController')
MFPhotoPickerController = _Class('MFPhotoPickerController')
MFContaineeInputViewController = _Class('MFContaineeInputViewController')
MFMailComposeRemoteViewController = _Class('MFMailComposeRemoteViewController')
MFMessageComposeViewController = _Class('MFMessageComposeViewController')
MFMailComposeViewController = _Class('MFMailComposeViewController')
MFGroupDetailViewController = _Class('MFGroupDetailViewController')
MFAutocompleteResultsTableViewController = _Class('MFAutocompleteResultsTableViewController')