
'''
Classes from the 'MLCompute' framework.
'''
    
try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None
        
def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None
    
    
MLCDeviceGPUHeapAllocator = _Class('MLCDeviceGPUHeapAllocator')
MLCLog = _Class('MLCLog')
MLCTensor = _Class('MLCTensor')
MLCStrings = _Class('MLCStrings')
MLCConvolutionDescriptor = _Class('MLCConvolutionDescriptor')
MLCDataHelper = _Class('MLCDataHelper')
MLCMatMulDescriptor = _Class('MLCMatMulDescriptor')
MLCEmbeddingDescriptor = _Class('MLCEmbeddingDescriptor')
MLCYOLOLossDescriptor = _Class('MLCYOLOLossDescriptor')
MLCOptimizerDescriptor = _Class('MLCOptimizerDescriptor')
MLCDeviceCPU = _Class('MLCDeviceCPU')
MLCTensorData = _Class('MLCTensorData')
MLCCustomLayerTensor = _Class('MLCCustomLayerTensor')
MLCErrors = _Class('MLCErrors')
MLCMultiheadAttentionDescriptor = _Class('MLCMultiheadAttentionDescriptor')
MLCOptimizer = _Class('MLCOptimizer')
MLCAdamOptimizer = _Class('MLCAdamOptimizer')
MLCRMSPropOptimizer = _Class('MLCRMSPropOptimizer')
MLCSGDOptimizer = _Class('MLCSGDOptimizer')
MLCTensorOptimizerDeviceData = _Class('MLCTensorOptimizerDeviceData')
MLCLossDescriptor = _Class('MLCLossDescriptor')
MLCControlTreeNode = _Class('MLCControlTreeNode')
MLCLSTMDescriptor = _Class('MLCLSTMDescriptor')
MLCGraph = _Class('MLCGraph')
MLCInferenceGraph = _Class('MLCInferenceGraph')
MLCTrainingGraph = _Class('MLCTrainingGraph')
MLCDeviceANE = _Class('MLCDeviceANE')
MLCTensorDescriptor = _Class('MLCTensorDescriptor')
MLCPoolingDescriptor = _Class('MLCPoolingDescriptor')
MLCDevice = _Class('MLCDevice')
MLCDeviceGPU = _Class('MLCDeviceGPU')
MLCPlatformInfo = _Class('MLCPlatformInfo')
MLCDeviceOptimizer = _Class('MLCDeviceOptimizer')
MLCTensorParameter = _Class('MLCTensorParameter')
MLCLayer = _Class('MLCLayer')
MLCCompareLayer = _Class('MLCCompareLayer')
MLCInstanceNormalizationLayer = _Class('MLCInstanceNormalizationLayer')
MLCLSTMLayer = _Class('MLCLSTMLayer')
MLCSplitLayer = _Class('MLCSplitLayer')
MLCArithmeticLayer = _Class('MLCArithmeticLayer')
MLCMatMulLayer = _Class('MLCMatMulLayer')
MLCConcatenationLayer = _Class('MLCConcatenationLayer')
MLCMultiheadAttentionLayer = _Class('MLCMultiheadAttentionLayer')
MLCActivationLayer = _Class('MLCActivationLayer')
MLCEmbeddingLayer = _Class('MLCEmbeddingLayer')
MLCSliceLayer = _Class('MLCSliceLayer')
MLCDropoutLayer = _Class('MLCDropoutLayer')
MLCPhiLayer = _Class('MLCPhiLayer')
MLCLayerNormalizationLayer = _Class('MLCLayerNormalizationLayer')
MLCReshapeLayer = _Class('MLCReshapeLayer')
MLCReductionLayer = _Class('MLCReductionLayer')
MLCSoftmaxLayer = _Class('MLCSoftmaxLayer')
MLCConvolutionLayer = _Class('MLCConvolutionLayer')
MLCGramMatrixLayer = _Class('MLCGramMatrixLayer')
MLCConditionalLayer = _Class('MLCConditionalLayer')
MLCUpsampleLayer = _Class('MLCUpsampleLayer')
MLCTransposeLayer = _Class('MLCTransposeLayer')
MLCFullyConnectedLayer = _Class('MLCFullyConnectedLayer')
MLCLossLayer = _Class('MLCLossLayer')
MLCYOLOLossLayer = _Class('MLCYOLOLossLayer')
MLCGroupNormalizationLayer = _Class('MLCGroupNormalizationLayer')
MLCPaddingLayer = _Class('MLCPaddingLayer')
MLCPoolingLayer = _Class('MLCPoolingLayer')
MLCBatchNormalizationLayer = _Class('MLCBatchNormalizationLayer')
MLCActivationDescriptor = _Class('MLCActivationDescriptor')
MLCDeviceOps = _Class('MLCDeviceOps')
MLCGPUDeviceOps = _Class('MLCGPUDeviceOps')
MLCMHAGPUDeviceOps = _Class('MLCMHAGPUDeviceOps')
MLCLayerNormGPUDeviceOps = _Class('MLCLayerNormGPUDeviceOps')
MLCMultiGPUDeviceOps = _Class('MLCMultiGPUDeviceOps')
MLCRNNGPUDeviceOps = _Class('MLCRNNGPUDeviceOps')
MLCANEDeviceOps = _Class('MLCANEDeviceOps')
MLCCPUDeviceOps = _Class('MLCCPUDeviceOps')
MLCSliceCPUDeviceOps = _Class('MLCSliceCPUDeviceOps')
MLCRNNCPUDeviceOps = _Class('MLCRNNCPUDeviceOps')
MLCMHACPUDeviceOps = _Class('MLCMHACPUDeviceOps')
MLCGPUHelper = _Class('MLCGPUHelper')