
'''
Classes from the 'Pyto' framework.
'''
    
try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None
        
def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None
    
    
Pyto.DefinitionsDataSource = _Class('Pyto.DefinitionsDataSource')
Pyto.ExpansionState = _Class('Pyto.ExpansionState')
Pyto.Parser = _Class('Pyto.Parser')
Pyto.PythonLexer = _Class('Pyto.PythonLexer')
Pyto.ViewControllerStore = _Class('Pyto.ViewControllerStore')
Pyto.RecentDataSource = _Class('Pyto.RecentDataSource')
Pyto.CurrentViewStore = _Class('Pyto.CurrentViewStore')
Pyto.SelectedItemStore = _Class('Pyto.SelectedItemStore')
Pyto.PyPiIndex = _Class('Pyto.PyPiIndex')
Pyto.SceneStateStore = _Class('Pyto.SceneStateStore')
Pyto.MemoryManager = _Class('Pyto.MemoryManager')
Pyto.Static = _Class('Pyto.Static')
Pyto.Localizable = _Class('Pyto.Localizable')
BlockBasedSelector = _Class('BlockBasedSelector')
RMProductsRequestDelegate = _Class('RMProductsRequestDelegate')
RMStore = _Class('RMStore')
RMAddPaymentParameters = _Class('RMAddPaymentParameters')
RMStoreAppReceiptVerifier = _Class('RMStoreAppReceiptVerifier')
CaptureDelegate = _Class('CaptureDelegate')
Pyto.RunCodeIntentHandler = _Class('Pyto.RunCodeIntentHandler')
Pyto.WidgetView = _Class('Pyto.WidgetView')
Pyto.InternetConnection = _Class('Pyto.InternetConnection')
Pyto.PyNotificationCenter = _Class('Pyto.PyNotificationCenter')
Pyto.BackgroundTask = _Class('Pyto.BackgroundTask')
Pyto.RunScriptIntentHandler = _Class('Pyto.RunScriptIntentHandler')
Pyto.RemoteNotifications = _Class('Pyto.RemoteNotifications')
Pyto.PyExtensionContext = _Class('Pyto.PyExtensionContext')
Pyto.WidgetComponent = _Class('Pyto.WidgetComponent')
Pyto.WidgetImage = _Class('Pyto.WidgetImage')
Pyto.WidgetSymbol = _Class('Pyto.WidgetSymbol')
Pyto.WidgetText = _Class('Pyto.WidgetText')
Pyto.WidgetDate = _Class('Pyto.WidgetDate')
NSKVONotifying__UIHyperAsymmetricExtender = _Class('NSKVONotifying__UIHyperAsymmetricExtender')
NSTemporaryObjectID_default = _Class('NSTemporaryObjectID_default')
Pyto.PyTableViewSection = _Class('Pyto.PyTableViewSection')
Pyto.PyTextInputTraitsConstants = _Class('Pyto.PyTextInputTraitsConstants')
Pyto.PyWrapper = _Class('Pyto.PyWrapper')
Pyto.PyButtonItem = _Class('Pyto.PyButtonItem')
Pyto.PyGestureRecognizer = _Class('Pyto.PyGestureRecognizer')
Pyto.PyColor = _Class('Pyto.PyColor')
Pyto.PyView = _Class('Pyto.PyView')
Pyto.PyWebView = _Class('Pyto.PyWebView')
Pyto.PyTextView = _Class('Pyto.PyTextView')
Pyto.PyImageView = _Class('Pyto.PyImageView')
Pyto.PyTextField = _Class('Pyto.PyTextField')
Pyto.PyTableViewCell = _Class('Pyto.PyTableViewCell')
Pyto.PyTableView = _Class('Pyto.PyTableView')
Pyto.PyLabel = _Class('Pyto.PyLabel')
Pyto.PyControl = _Class('Pyto.PyControl')
Pyto.PySwitch = _Class('Pyto.PySwitch')
Pyto.PySegmentedControl = _Class('Pyto.PySegmentedControl')
Pyto.PySlider = _Class('Pyto.PySlider')
Pyto.PyButton = _Class('Pyto.PyButton')
Pyto.PyValue = _Class('Pyto.PyValue')
Pyto.PyWidget = _Class('Pyto.PyWidget')
WidgetTypeResolutionResult = _Class('WidgetTypeResolutionResult')
WidgetCategoryResolutionResult = _Class('WidgetCategoryResolutionResult')
WidgetCategory = _Class('WidgetCategory')
ScriptIntentResponse = _Class('ScriptIntentResponse')
GetScriptOutputIntentResponse = _Class('GetScriptOutputIntentResponse')
RunCodeIntentResponse = _Class('RunCodeIntentResponse')
RunScriptIntentResponse = _Class('RunScriptIntentResponse')
ScriptIntent = _Class('ScriptIntent')
GetScriptOutputIntent = _Class('GetScriptOutputIntent')
RunCodeIntent = _Class('RunCodeIntent')
RunScriptIntent = _Class('RunScriptIntent')
Pyto.ViewControllerTransitionCoordinator = _Class('Pyto.ViewControllerTransitionCoordinator')
NSKVONotifying__UIHyperConstantExtender = _Class('NSKVONotifying__UIHyperConstantExtender')
NSKVONotifying__UIHyperspace = _Class('NSKVONotifying__UIHyperspace')
NSKVONotifying__UIHyperrectangle = _Class('NSKVONotifying__UIHyperrectangle')
NSKVONotifying__UIHyperregionUnion = _Class('NSKVONotifying__UIHyperregionUnion')
NSKVONotifying__UIHyperpoint = _Class('NSKVONotifying__UIHyperpoint')
Pyto.MovableTextField = _Class('Pyto.MovableTextField')
Pyto.FolderDocument = _Class('Pyto.FolderDocument')
Pyto.PyDocument = _Class('Pyto.PyDocument')
ExtensionsInitializer = _Class('ExtensionsInitializer')
Pyto.PyCallbackHelper = _Class('Pyto.PyCallbackHelper')
Pyto.ReviewHelper = _Class('Pyto.ReviewHelper')
Pyto._Selector = _Class('Pyto._Selector')
Pyto.PySelector = _Class('Pyto.PySelector')
Pyto.QuickLookHelper = _Class('Pyto.QuickLookHelper')
Pyto.PySpeech = _Class('Pyto.PySpeech')
Pyto.PyTurtle = _Class('Pyto.PyTurtle')
Pyto.PyMotionHelper = _Class('Pyto.PyMotionHelper')
Pyto.PyMultipeerHelper = _Class('Pyto.PyMultipeerHelper')
Pyto.PyPhotosHelper = _Class('Pyto.PyPhotosHelper')
Pyto.PyMusicHelper = _Class('Pyto.PyMusicHelper')
Pyto.PyAlert = _Class('Pyto.PyAlert')
Pyto.PyFilePicker = _Class('Pyto.PyFilePicker')
Pyto.PyLocationHelper = _Class('Pyto.PyLocationHelper')
Pyto.PySharingHelper = _Class('Pyto.PySharingHelper')
Pyto.PyOutputHelper = _Class('Pyto.PyOutputHelper')
Pyto.PyInputHelper = _Class('Pyto.PyInputHelper')
Pyto.PyThread = _Class('Pyto.PyThread')
Pyto.PyMainThread = _Class('Pyto.PyMainThread')
Pyto.PyCore = _Class('Pyto.PyCore')
DeallocationObserver = _Class('DeallocationObserver')
RMAppReceipt = _Class('RMAppReceipt')
RMAppReceiptIAP = _Class('RMAppReceiptIAP')
LineNumberLayoutManager = _Class('LineNumberLayoutManager')
BSXPCServiceConnectionProxy<PSPointerDefaultServiceClientToServerInterface> = _Class('BSXPCServiceConnectionProxy<PSPointerDefaultServiceClientToServerInterface>')
BSXPCServiceConnectionProxy<UISApplicationSupportXPCServerInterface> = _Class('BSXPCServiceConnectionProxy<UISApplicationSupportXPCServerInterface>')
BSXPCServiceConnectionProxy<FBSWorkspaceServiceClientInterface> = _Class('BSXPCServiceConnectionProxy<FBSWorkspaceServiceClientInterface>')
NSKVONotifying_CALayer = _Class('NSKVONotifying_CALayer')
NSKVONotifying_NSUserDefaults = _Class('NSKVONotifying_NSUserDefaults')
Pyto.Python = _Class('Pyto.Python')
Pyto.SceneDelegate = _Class('Pyto.SceneDelegate')
LineNumberTextViewWrapper = _Class('LineNumberTextViewWrapper')
Pyto.LoadingPythonView = _Class('Pyto.LoadingPythonView')
Pyto.ReplaceView = _Class('Pyto.ReplaceView')
NSKVONotifying__UISplitViewControllerPanelImplView = _Class('NSKVONotifying__UISplitViewControllerPanelImplView')
NSKVONotifying_SavannaKit.InnerTextView = _Class('NSKVONotifying_SavannaKit.InnerTextView')
Pyto.ConsoleTextView = _Class('Pyto.ConsoleTextView')
LineNumberTextView = _Class('LineNumberTextView')
Pyto.EditorTextView = _Class('Pyto.EditorTextView')
NSKVONotifying_Pyto.EditorTextView = _Class('NSKVONotifying_Pyto.EditorTextView')
Pyto.HeaderLabel = _Class('Pyto.HeaderLabel')
MarqueeLabel.MarqueeLabel = _Class('MarqueeLabel.MarqueeLabel')
NSKVONotifying_UITextField = _Class('NSKVONotifying_UITextField')
Pyto.AppDelegate = _Class('Pyto.AppDelegate')
Pyto.WidgetSimulatorViewController = _Class('Pyto.WidgetSimulatorViewController')
Pyto.MarkdownPreviewController = _Class('Pyto.MarkdownPreviewController')
Pyto.ScriptSettingsViewController = _Class('Pyto.ScriptSettingsViewController')
Pyto.ActivityViewController = _Class('Pyto.ActivityViewController')
Pyto.ContainerViewController = _Class('Pyto.ContainerViewController')
Pyto.EditorViewController = _Class('Pyto.EditorViewController')
Pyto.EditorSplitViewController = _Class('Pyto.EditorSplitViewController')
Pyto.PipInstallerViewController = _Class('Pyto.PipInstallerViewController')
Pyto.RunModuleViewController = _Class('Pyto.RunModuleViewController')
Pyto.REPLViewController = _Class('Pyto.REPLViewController')
Pyto.DocumentationViewController = _Class('Pyto.DocumentationViewController')
Pyto.AcknowledgmentsViewController = _Class('Pyto.AcknowledgmentsViewController')
Pyto.ThemableNavigationController = _Class('Pyto.ThemableNavigationController')
Pyto.ConsoleViewController = _Class('Pyto.ConsoleViewController')
Pyto.WatchInputSuggestionsTableViewController = _Class('Pyto.WatchInputSuggestionsTableViewController')
Pyto.TemplateChooserTableViewController = _Class('Pyto.TemplateChooserTableViewController')
Pyto.ThemeChooserTableViewController = _Class('Pyto.ThemeChooserTableViewController')
Pyto.FileBrowserViewController = _Class('Pyto.FileBrowserViewController')
Pyto.EditorActionsTableViewController = _Class('Pyto.EditorActionsTableViewController')
Pyto.ResolveConflictsTableViewController = _Class('Pyto.ResolveConflictsTableViewController')
Pyto.CustomIconTableViewController = _Class('Pyto.CustomIconTableViewController')
Pyto.ProjectsBrowserViewController = _Class('Pyto.ProjectsBrowserViewController')
Pyto.ThemeMakerTableViewController = _Class('Pyto.ThemeMakerTableViewController')
Pyto.PipViewController = _Class('Pyto.PipViewController')
Pyto.AboutTableViewController = _Class('Pyto.AboutTableViewController')
Pyto.ModulesTableViewController = _Class('Pyto.ModulesTableViewController')
Pyto.MenuTableViewController = _Class('Pyto.MenuTableViewController')
Pyto.FoldersBrowserViewController = _Class('Pyto.FoldersBrowserViewController')
Pyto.DocumentBrowserViewController = _Class('Pyto.DocumentBrowserViewController')