'''
Classes from the 'QuartzCore' framework.
'''
    
try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None
        
def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None
    
    
CARenderer = _Class('CARenderer')
CAStateController = _Class('CAStateController')
CADisplayPersistedPreferredMode = _Class('CADisplayPersistedPreferredMode')
CADisplayPersistedLatency = _Class('CADisplayPersistedLatency')
CADisplayPersistedData = _Class('CADisplayPersistedData')
CASlotProxy = _Class('CASlotProxy')
CAMLWriter = _Class('CAMLWriter')
CAEmitterBehavior = _Class('CAEmitterBehavior')
CATransactionCompletionItem = _Class('CATransactionCompletionItem')
CAPackage = _Class('CAPackage')
CAPresentationModifier = _Class('CAPresentationModifier')
CAPresentationModifierGroup = _Class('CAPresentationModifierGroup')
CAWindowServerDisplay = _Class('CAWindowServerDisplay')
CAWindowServerVirtualDisplay = _Class('CAWindowServerVirtualDisplay')
CAWindowServer = _Class('CAWindowServer')
CAMetalDrawable = _Class('CAMetalDrawable')
CAStateTransitionElement = _Class('CAStateTransitionElement')
CADisplayFlipBook = _Class('CADisplayFlipBook')
CAStateControllerLayer = _Class('CAStateControllerLayer')
CAStateControllerAnimation = _Class('CAStateControllerAnimation')
CAEmitterCell = _Class('CAEmitterCell')
CAStateTransition = _Class('CAStateTransition')
CAStateElement = _Class('CAStateElement')
CAStateRemoveElement = _Class('CAStateRemoveElement')
CAStateSetValue = _Class('CAStateSetValue')
CAStateAddElement = _Class('CAStateAddElement')
CAStateAddAnimation = _Class('CAStateAddAnimation')
CAStateRemoveAnimation = _Class('CAStateRemoveAnimation')
CAValueFunction = _Class('CAValueFunction')
CAMeshTransform = _Class('CAMeshTransform')
CAMeshInterpolator = _Class('CAMeshInterpolator')
CAMutableMeshTransform = _Class('CAMutableMeshTransform')
CAState = _Class('CAState')
CAMLParser = _Class('CAMLParser')
CAStateControllerUndo = _Class('CAStateControllerUndo')
CACodingCAMLWriterDelegate = _Class('CACodingCAMLWriterDelegate')
CADebuggingArchiverDelegate = _Class('CADebuggingArchiverDelegate')
CACGPathCodingSegment = _Class('CACGPathCodingSegment')
CACodingProxy = _Class('CACodingProxy')
CAIOSurfaceCodingProxy = _Class('CAIOSurfaceCodingProxy')
CACGPathCodingProxy = _Class('CACGPathCodingProxy')
CACGPatternCodingProxy = _Class('CACGPatternCodingProxy')
LKCGImageCodingProxy = _Class('LKCGImageCodingProxy')
LKCGColorCodingProxy = _Class('LKCGColorCodingProxy')
LKNSValueCodingProxy = _Class('LKNSValueCodingProxy')
LKNSDictionaryCodingProxy = _Class('LKNSDictionaryCodingProxy')
LKNSArrayCodingProxy = _Class('LKNSArrayCodingProxy')
CADisplayModeCriteria = _Class('CADisplayModeCriteria')
CADisplayPreferences = _Class('CADisplayPreferences')
CAMutableDisplayPreferences = _Class('CAMutableDisplayPreferences')
CADisplayProperties = _Class('CADisplayProperties')
CADisplayAttributes = _Class('CADisplayAttributes')
CADisplayMode = _Class('CADisplayMode')
CAStateControllerTransition = _Class('CAStateControllerTransition')
CATintedImage = _Class('CATintedImage')
CAMediaTimingFunction = _Class('CAMediaTimingFunction')
CAMediaTimingFunctionBuiltin = _Class('CAMediaTimingFunctionBuiltin')
CAFenceHandle = _Class('CAFenceHandle')
CAContext = _Class('CAContext')
CAFilter = _Class('CAFilter')
CATransaction = _Class('CATransaction')
CADisplayLink = _Class('CADisplayLink')
CASuspendNotification = _Class('CASuspendNotification')
CADisplay = _Class('CADisplay')
CAAnimation = _Class('CAAnimation')
CAMatchPropertyAnimation = _Class('CAMatchPropertyAnimation')
CAMatchMoveAnimation = _Class('CAMatchMoveAnimation')
CAAnimationGroup = _Class('CAAnimationGroup')
CAPropertyAnimation = _Class('CAPropertyAnimation')
CABasicAnimation = _Class('CABasicAnimation')
CASpringAnimation = _Class('CASpringAnimation')
CAExternalAnimation = _Class('CAExternalAnimation')
CAKeyframeAnimation = _Class('CAKeyframeAnimation')
CATransition = _Class('CATransition')
CALayer = _Class('CALayer')
CADistanceFieldLayer = _Class('CADistanceFieldLayer')
CALinearMaskLayer = _Class('CALinearMaskLayer')
CAPortalLayer = _Class('CAPortalLayer')
CAScrollLayer = _Class('CAScrollLayer')
CAChameleonLayer = _Class('CAChameleonLayer')
CAEmitterLayer = _Class('CAEmitterLayer')
CAEAGLLayer = _Class('CAEAGLLayer')
CATextLayer = _Class('CATextLayer')
CASmoothedTextLayer = _Class('CASmoothedTextLayer')
CAMetalLayer = _Class('CAMetalLayer')
CAGradientLayer = _Class('CAGradientLayer')
CAReplicatorLayer = _Class('CAReplicatorLayer')
CAShapeLayer = _Class('CAShapeLayer')
CALayerHost = _Class('CALayerHost')
CABackdropLayer = _Class('CABackdropLayer')
CATransformLayer = _Class('CATransformLayer')
CATiledLayer = _Class('CATiledLayer')
CALayerArray = _Class('CALayerArray')