'''
Classes from the 'QuickLook' framework.
'''

try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None

    
QLItem = _Class('QLItem')
QLImageAnimationTimer = _Class('QLImageAnimationTimer')
QLToolbarButton = _Class('QLToolbarButton')
QLToolbarButtonOption = _Class('QLToolbarButtonOption')
QLSingleItemThumbnailGenerator = _Class('QLSingleItemThumbnailGenerator')
QLAppearance = _Class('QLAppearance')
QLCustomItemViewControllerHostProxy = _Class('QLCustomItemViewControllerHostProxy')
QLCustomURLSharingProxyDelegate = _Class('QLCustomURLSharingProxyDelegate')
QLDetailItemViewControllerState = _Class('QLDetailItemViewControllerState')
QLAnimatedImage = _Class('QLAnimatedImage')
QLPreviewContext = _Class('QLPreviewContext')
QLImageData = _Class('QLImageData')
QLDictionaryItemTransformer = _Class('QLDictionaryItemTransformer')
QLItemThumbnailGenerator = _Class('QLItemThumbnailGenerator')
QLPreviewMockScene = _Class('QLPreviewMockScene')
QLTextItemTransformer = _Class('QLTextItemTransformer')
QLStringWrapper = _Class('QLStringWrapper')
QLNotificationCenter = _Class('QLNotificationCenter')
QLKeyCommand = _Class('QLKeyCommand')
QLPreviewParts = _Class('QLPreviewParts')
QLBasePreviewParts = _Class('QLBasePreviewParts')
QLThreadInvoker = _Class('QLThreadInvoker')
QLItemFetcherFactory = _Class('QLItemFetcherFactory')
QLNetworkStateObserver = _Class('QLNetworkStateObserver')
QLPinchRotationTracker = _Class('QLPinchRotationTracker')
QLMediaItemTransformer = _Class('QLMediaItemTransformer')
QLThumbnail = _Class('QLThumbnail')
QLThumbnailDescriptor = _Class('QLThumbnailDescriptor')
QLDataItemTransformer = _Class('QLDataItemTransformer')
QLURLItemTransformer = _Class('QLURLItemTransformer')
QLItemTransformer = _Class('QLItemTransformer')
QLPHSwipeDownTracker = _Class('QLPHSwipeDownTracker')
QLSwipeDownTracker = _Class('QLSwipeDownTracker')
QLWaveformScrubberViewProvider = _Class('QLWaveformScrubberViewProvider')
QLContactItemTransformer = _Class('QLContactItemTransformer')
QLSpotlightSearchableItemInfo = _Class('QLSpotlightSearchableItemInfo')
QLPreviewItemEditedCopy = _Class('QLPreviewItemEditedCopy')
QLListCellManager = _Class('QLListCellManager')
QLPXSwipeDownTracker = _Class('QLPXSwipeDownTracker')
QLPreviewItemStore = _Class('QLPreviewItemStore')
QLDataSource = _Class('QLDataSource')
QLCacheItem = _Class('QLCacheItem')
QLRemoteItemTransformer = _Class('QLRemoteItemTransformer')
QLImageItemTransformer = _Class('QLImageItemTransformer')
QLImageItemContentsTransformer = _Class('QLImageItemContentsTransformer')
QLTransitionDriver = _Class('QLTransitionDriver')
QLSlideTransitionDriver = _Class('QLSlideTransitionDriver')
QLZoomTransitionDriver = _Class('QLZoomTransitionDriver')
QLTransitionContext = _Class('QLTransitionContext')
QLTransitionController = _Class('QLTransitionController')
QLInteractiveTransitionController = _Class('QLInteractiveTransitionController')
QLLivePhotoItemTransformer = _Class('QLLivePhotoItemTransformer')
QLMovieEdits = _Class('QLMovieEdits')
QLPUAnimationGroup = _Class('QLPUAnimationGroup')
QLPULayerAnimation = _Class('QLPULayerAnimation')
QLPUTimedAnimationGroup = _Class('QLPUTimedAnimationGroup')
QLPULayerAnimationGroup = _Class('QLPULayerAnimationGroup')
QLPreviewConverter = _Class('QLPreviewConverter')
QLItemFetcher = _Class('QLItemFetcher')
QLSpotlightFetcher = _Class('QLSpotlightFetcher')
QLItemProviderFetcher = _Class('QLItemProviderFetcher')
QLUbiquitousItemFetcher = _Class('QLUbiquitousItemFetcher')
QLFPItemFetcher = _Class('QLFPItemFetcher')
QLDataFetcher = _Class('QLDataFetcher')
QLDismissAction = _Class('QLDismissAction')
QLEditedItem = _Class('QLEditedItem')
QLToolbarController = _Class('QLToolbarController')
QLPXObservable = _Class('QLPXObservable')
QLPXNumberFilter = _Class('QLPXNumberFilter')
QLPXVelocityNumberFilter = _Class('QLPXVelocityNumberFilter')
QLPXChangeDirectionNumberFilter = _Class('QLPXChangeDirectionNumberFilter')
QLPXInitialHysteresisNumberFilter = _Class('QLPXInitialHysteresisNumberFilter')
QLPXAngleNumberFilter = _Class('QLPXAngleNumberFilter')
QLPXCompoundNumberFilter = _Class('QLPXCompoundNumberFilter')
QLImageItemContents = _Class('QLImageItemContents')
QLImageItemDataContents = _Class('QLImageItemDataContents')
QLImageItemURLContents = _Class('QLImageItemURLContents')
QLNavigationState = _Class('QLNavigationState')
QLStateManagerProxy = _Class('QLStateManagerProxy')
QLActivityItemProvider = _Class('QLActivityItemProvider')
QLPreviewPrinter = _Class('QLPreviewPrinter')
QLPreviewItemPrinter = _Class('QLPreviewItemPrinter')
QLPreviewExtensionServiceContext_iOS = _Class('QLPreviewExtensionServiceContext_iOS')
QLPreviewExtensionHostContext = _Class('QLPreviewExtensionHostContext')
QLPreviewCollectionServiceContext = _Class('QLPreviewCollectionServiceContext')
QLPreviewCollectionHostContext = _Class('QLPreviewCollectionHostContext')
QLToolbarButtonItemRepresentation = _Class('QLToolbarButtonItemRepresentation')
QLBarButtonItem = _Class('QLBarButtonItem')
QLPreviewURLProtocol = _Class('QLPreviewURLProtocol')
QLMediaScrubberGesture = _Class('QLMediaScrubberGesture')
QLRoundProgressLayer = _Class('QLRoundProgressLayer')
QLThumbnailCreationOperation = _Class('QLThumbnailCreationOperation')
QLAsynchronousBlockOperation = _Class('QLAsynchronousBlockOperation')
QLListCellDataGenerationOperation = _Class('QLListCellDataGenerationOperation')
QLItemThumbnailGenerationOperation = _Class('QLItemThumbnailGenerationOperation')
QLOverlayPlayButton = _Class('QLOverlayPlayButton')
QLThumbnailView = _Class('QLThumbnailView')
QLVideoScrubberView = _Class('QLVideoScrubberView')
QLRoundProgressView = _Class('QLRoundProgressView')
QLWaveformView = _Class('QLWaveformView')
QLPageNumberView = _Class('QLPageNumberView')
QLScrubView = _Class('QLScrubView')
QLPreviewControllerView = _Class('QLPreviewControllerView')
QLErrorView = _Class('QLErrorView')
QLListCell = _Class('QLListCell')
QLPreviewScrollView = _Class('QLPreviewScrollView')
QLFileIconImageView = _Class('QLFileIconImageView')
QLPreviewCollection = _Class('QLPreviewCollection')
QLCustomItemViewController = _Class('QLCustomItemViewController')
QLServiceViewController = _Class('QLServiceViewController')
QLPreviewController = _Class('QLPreviewController')
QLItemViewController = _Class('QLItemViewController')
QLErrorItemViewController = _Class('QLErrorItemViewController')
QLRemoteItemViewController = _Class('QLRemoteItemViewController')
QLPasswordItemViewController = _Class('QLPasswordItemViewController')
QLDetailItemViewController = _Class('QLDetailItemViewController')
QLDownloadingItemViewController = _Class('QLDownloadingItemViewController')
QLLoadingItemViewController = _Class('QLLoadingItemViewController')
QLWebLocationItemViewController = _Class('QLWebLocationItemViewController')
QLScrollableContentItemViewController = _Class('QLScrollableContentItemViewController')
QLImageItemViewController = _Class('QLImageItemViewController')
QLLivePhotoItemViewController = _Class('QLLivePhotoItemViewController')
QLMediaItemBaseViewController = _Class('QLMediaItemBaseViewController')
QLMediaItemViewController = _Class('QLMediaItemViewController')
QLMovieItemViewController = _Class('QLMovieItemViewController')
QLAudioItemViewController = _Class('QLAudioItemViewController')
QLLoopingMediaItemViewController = _Class('QLLoopingMediaItemViewController')
QLDebugItemViewController = _Class('QLDebugItemViewController')
QLTextItemViewController = _Class('QLTextItemViewController')
QLWKWebItemViewController = _Class('QLWKWebItemViewController')
QLAVPlayerItemViewController = _Class('QLAVPlayerItemViewController')
QLItemAggregatedViewController = _Class('QLItemAggregatedViewController')
QLMovieItemAggregatedViewController = _Class('QLMovieItemAggregatedViewController')
QLItemPresenterViewController = _Class('QLItemPresenterViewController')
QLScreenTimeItemViewController = _Class('QLScreenTimeItemViewController')
QLPageViewController = _Class('QLPageViewController')
QLRemotePreviewHostViewController = _Class('QLRemotePreviewHostViewController')
QLRemotePreviewCollection = _Class('QLRemotePreviewCollection')
QLRemoteAccessoryViewController = _Class('QLRemoteAccessoryViewController')
QLListViewController = _Class('QLListViewController')
QLDelegateProxy = _Class('QLDelegateProxy')
