'''
Classes from the 'SafariServices' framework.
'''

try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None


def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None

    
SFCustomActivityProxy = _Class('SFCustomActivityProxy')
SFContentBlockerState = _Class('SFContentBlockerState')
SFHighPriorityRecommendationData = _Class('SFHighPriorityRecommendationData')
SFSafariViewControllerConfiguration = _Class('SFSafariViewControllerConfiguration')
SFNavigationBarMetrics = _Class('SFNavigationBarMetrics')
SFTelephonyURLHandler = _Class('SFTelephonyURLHandler')
SFTelephonyURLRequest = _Class('SFTelephonyURLRequest')
SFDownloadFile = _Class('SFDownloadFile')
SFFormAutoFillFrame = _Class('SFFormAutoFillFrame')
SFFolderPickerList = _Class('SFFolderPickerList')
SFAutoFillAuthenticationUtilities = _Class('SFAutoFillAuthenticationUtilities')
SFBrowserStateSQLiteStore = _Class('SFBrowserStateSQLiteStore')
SFProcessDictionary = _Class('SFProcessDictionary')
SFCertificateWarningJSController = _Class('SFCertificateWarningJSController')
SFWebProcessPlugInCertificateWarningController = _Class('SFWebProcessPlugInCertificateWarningController')
SFCredentialDisplayData = _Class('SFCredentialDisplayData')
SFDialogAction = _Class('SFDialogAction')
SFWebProcessPlugInPageExtensionController = _Class('SFWebProcessPlugInPageExtensionController')
SFBlockBasedCAAnimationDelegate = _Class('SFBlockBasedCAAnimationDelegate')
SFUIBarButtonItemPopoverSourceInfo = _Class('SFUIBarButtonItemPopoverSourceInfo')
SFWatchMetrics = _Class('SFWatchMetrics')
SFFormAutocompleteState = _Class('SFFormAutocompleteState')
SFContactAutoFillValue = _Class('SFContactAutoFillValue')
SFSystemAlert = _Class('SFSystemAlert')
SFPrivacyReportGridRowLayoutInfo = _Class('SFPrivacyReportGridRowLayoutInfo')
SFWebUIDialog = _Class('SFWebUIDialog')
SFBasicDialog = _Class('SFBasicDialog')
SFAuthenticatorDialog = _Class('SFAuthenticatorDialog')
SFBrowserPersonaAnalyticsHelper = _Class('SFBrowserPersonaAnalyticsHelper')
SFContactAutoFillPropertyValues = _Class('SFContactAutoFillPropertyValues')
SFStartPageBookmarkFolderDataSource = _Class('SFStartPageBookmarkFolderDataSource')
SFLocationManager = _Class('SFLocationManager')
SFBrowserDocumentTrackerInfo = _Class('SFBrowserDocumentTrackerInfo')
SFPrintQueueItem = _Class('SFPrintQueueItem')
SFFormAutoFillFrameHandle = _Class('SFFormAutoFillFrameHandle')
SFNavigationBarAccessoryButtonArrangement = _Class('SFNavigationBarAccessoryButtonArrangement')
SFContentBlockerManager = _Class('SFContentBlockerManager')
SFFormAutoFillNode = _Class('SFFormAutoFillNode')
SFDownloadStorageUsageMonitorEntry = _Class('SFDownloadStorageUsageMonitorEntry')
SFAuthenticationSession = _Class('SFAuthenticationSession')
SFFormsMetadataProvider = _Class('SFFormsMetadataProvider')
SFPrivacyReportItem = _Class('SFPrivacyReportItem')
SSReadingList = _Class('SSReadingList')
SFHighPriorityRecommendationCellID = _Class('SFHighPriorityRecommendationCellID')
SFPasswordCellData = _Class('SFPasswordCellData')
SFBookmarkTouchIconRequest = _Class('SFBookmarkTouchIconRequest')
SFFeatureManager = _Class('SFFeatureManager')
SFSingleCreditCardData = _Class('SFSingleCreditCardData')
SFInteractiveDismissController = _Class('SFInteractiveDismissController')
SFPrintPageRenderer = _Class('SFPrintPageRenderer')
SFMultipleLineAlertAction = _Class('SFMultipleLineAlertAction')
SFKillSafariViewServiceActivity = _Class('SFKillSafariViewServiceActivity')
SFSaveToFilesActivity = _Class('SFSaveToFilesActivity')
SFHostApplicationCustomActivity = _Class('SFHostApplicationCustomActivity')
SFKBScreenTraits = _Class('SFKBScreenTraits')
SFDownloadsBarButtonItem = _Class('SFDownloadsBarButtonItem')
SFBarButtonItemLongPressGestureRecognizer = _Class('SFBarButtonItemLongPressGestureRecognizer')
SFToggleBackgroundLayer = _Class('SFToggleBackgroundLayer')
SFBarRegistration = _Class('SFBarRegistration')
SFAutomaticPasswordExplanationView = _Class('SFAutomaticPasswordExplanationView')
SFAutomaticPasswordScrollViewContentView = _Class('SFAutomaticPasswordScrollViewContentView')
SFQRImageContentView = _Class('SFQRImageContentView')
SFQRImageHeaderView = _Class('SFQRImageHeaderView')
SFDialogTextView = _Class('SFDialogTextView')
SFPrivacyReportExplanationDetailItemView = _Class('SFPrivacyReportExplanationDetailItemView')
SFPrivacyReportMeterBar = _Class('SFPrivacyReportMeterBar')
SFSafariLaunchPlaceholderView = _Class('SFSafariLaunchPlaceholderView')
SFNanoDomainContainerView = _Class('SFNanoDomainContainerView')
SFSafariView = _Class('SFSafariView')
SFReaderAppearanceThemeSelector = _Class('SFReaderAppearanceThemeSelector')
SFDomainLabel = _Class('SFDomainLabel')
SFPrivacyReportOverviewCellContentView = _Class('SFPrivacyReportOverviewCellContentView')
SFSiteCardSourceView = _Class('SFSiteCardSourceView')
SFToggleBackgroundView = _Class('SFToggleBackgroundView')
SFPrivacyReportIconView = _Class('SFPrivacyReportIconView')
SFPrivacyReportGridView = _Class('SFPrivacyReportGridView')
SFPrivacyReportExplanationDetailView = _Class('SFPrivacyReportExplanationDetailView')
SFPrivacyReportOverviewView = _Class('SFPrivacyReportOverviewView')
SFDialogContentView = _Class('SFDialogContentView')
SFToolbarContainer = _Class('SFToolbarContainer')
SFContactAutoFillTableViewCell = _Class('SFContactAutoFillTableViewCell')
SFSecurityRecommendationInfoCell = _Class('SFSecurityRecommendationInfoCell')
SFPrivacyReportTrackingTableViewCell = _Class('SFPrivacyReportTrackingTableViewCell')
SFPrivacyReportWebsiteTableViewCell = _Class('SFPrivacyReportWebsiteTableViewCell')
SFPrivacyReportTrackerTableViewCell = _Class('SFPrivacyReportTrackerTableViewCell')
SFPasswordTableViewCell = _Class('SFPasswordTableViewCell')
SFPrivacyReportExplanationTableViewCell = _Class('SFPrivacyReportExplanationTableViewCell')
SFSwitchTableViewCell = _Class('SFSwitchTableViewCell')
SFPrivacyReportGridTableViewCell = _Class('SFPrivacyReportGridTableViewCell')
SFPrivacyReportSubheaderTableViewCell = _Class('SFPrivacyReportSubheaderTableViewCell')
SFPasswordBreachToggleCell = _Class('SFPasswordBreachToggleCell')
SFEditableTableViewCell = _Class('SFEditableTableViewCell')
SFPrivacyReportDetailToggleTableViewCell = _Class('SFPrivacyReportDetailToggleTableViewCell')
SFStartPageSectionHeader = _Class('SFStartPageSectionHeader')
SFBannerCell = _Class('SFBannerCell')
SFSiteIconCell = _Class('SFSiteIconCell')
SFSiteCardCell = _Class('SFSiteCardCell')
SFPrivacyReportGridItemCell = _Class('SFPrivacyReportGridItemCell')
SFAutomaticPasswordInputView = _Class('SFAutomaticPasswordInputView')
SFDialogTextField = _Class('SFDialogTextField')
SFDismissButton = _Class('SFDismissButton')
SFDownloadsBarButtonItemView = _Class('SFDownloadsBarButtonItemView')
SFNavigationBarToggleButton = _Class('SFNavigationBarToggleButton')
SFLinkPreviewHeaderContentView = _Class('SFLinkPreviewHeaderContentView')
SFVibrantCellSelectionBackgroundView = _Class('SFVibrantCellSelectionBackgroundView')
SFStartPageCollectionViewController = _Class('SFStartPageCollectionViewController')
SFWebViewController = _Class('SFWebViewController')
SFReaderEnabledWebViewController = _Class('SFReaderEnabledWebViewController')
SFPasswordServiceViewController = _Class('SFPasswordServiceViewController')
SFExternalPasswordCredentialServiceViewController = _Class('SFExternalPasswordCredentialServiceViewController')
SFPasswordSavingServiceViewController = _Class('SFPasswordSavingServiceViewController')
SFPasswordPickerServiceViewController = _Class('SFPasswordPickerServiceViewController')
SFBrowserServiceViewController = _Class('SFBrowserServiceViewController')
SFReaderViewController = _Class('SFReaderViewController')
SFPrivacyReportViewController = _Class('SFPrivacyReportViewController')
SFSafariViewController = _Class('SFSafariViewController')
SFAuthenticationViewController = _Class('SFAuthenticationViewController')
SFLinkRedirectionViewController = _Class('SFLinkRedirectionViewController')
SFPasswordAlertController = _Class('SFPasswordAlertController')
SFFormAutoFillMultipleLoginsAlertController = _Class('SFFormAutoFillMultipleLoginsAlertController')
SFBrowserRemoteViewController = _Class('SFBrowserRemoteViewController')
SFPasswordRemoteViewController = _Class('SFPasswordRemoteViewController')
SFExternalPasswordCredentialRemoteViewController = _Class('SFExternalPasswordCredentialRemoteViewController')
SFPasswordSavingRemoteViewController = _Class('SFPasswordSavingRemoteViewController')
SFPasswordPickerRemoteViewController = _Class('SFPasswordPickerRemoteViewController')
SFPasswordPickerViewController = _Class('SFPasswordPickerViewController')
SFAddPasswordViewController = _Class('SFAddPasswordViewController')
SFContactAutoFillViewController = _Class('SFContactAutoFillViewController')
SFPrivacyReportWebsiteDetailViewController = _Class('SFPrivacyReportWebsiteDetailViewController')
SFPrivacyReportTrackerDetailViewController = _Class('SFPrivacyReportTrackerDetailViewController')
SFContactAutoFillDetailViewController = _Class('SFContactAutoFillDetailViewController')
SFPasswordDetailViewController = _Class('SFPasswordDetailViewController')
SFQueueingServiceViewControllerProxy = _Class('SFQueueingServiceViewControllerProxy')
