
'''
Classes from the 'SearchFoundation' framework.
'''
    
try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None
        
def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None
    
    
SFUserActivityData = _Class('SFUserActivityData')
SFSportsTeam = _Class('SFSportsTeam')
SFCustom = _Class('SFCustom')
SFPBSerialization = _Class('SFPBSerialization')
SFTextColumnSection = _Class('SFTextColumnSection')
SFMapRegion = _Class('SFMapRegion')
SFTrack = _Class('SFTrack')
SFFlightLeg = _Class('SFFlightLeg')
SFButton = _Class('SFButton')
SFNamedProtobufMessage = _Class('SFNamedProtobufMessage')
SFPin = _Class('SFPin')
SFFlight = _Class('SFFlight')
SFProductInventoryResult = _Class('SFProductInventoryResult')
SFTableAlignmentSchema = _Class('SFTableAlignmentSchema')
SFTextColumn = _Class('SFTextColumn')
SFApiResults = _Class('SFApiResults')
SFCommandValue = _Class('SFCommandValue')
SFAirport = _Class('SFAirport')
SFLatLng = _Class('SFLatLng')
SFTitleSubtitleTuple = _Class('SFTitleSubtitleTuple')
ImageFileLoader = _Class('ImageFileLoader')
WeakLoader = _Class('WeakLoader')
SFProduct = _Class('SFProduct')
SFMessageAttachment = _Class('SFMessageAttachment')
SFTableColumnAlignment = _Class('SFTableColumnAlignment')
SFColor = _Class('SFColor')
SFPBCardSectionValueTranslator = _Class('SFPBCardSectionValueTranslator')
SFResultSection = _Class('SFResultSection')
WeakListener = _Class('WeakListener')
SFPunchout = _Class('SFPunchout')
SFAbstractCommand = _Class('SFAbstractCommand')
SFReferentialCommand = _Class('SFReferentialCommand')
SFProductAvailability = _Class('SFProductAvailability')
SFProductInventory = _Class('SFProductInventory')
SFDynamicURLImageResource = _Class('SFDynamicURLImageResource')
SFWatchListItem = _Class('SFWatchListItem')
SFMediaDetail = _Class('SFMediaDetail')
SFSearchSuggestion = _Class('SFSearchSuggestion')
SFUserActivityInfo = _Class('SFUserActivityInfo')
SFMediaItem = _Class('SFMediaItem')
SFKeyValueTuple = _Class('SFKeyValueTuple')
SFImageOption = _Class('SFImageOption')
SFAppLink = _Class('SFAppLink')
SFCardSectionValue = _Class('SFCardSectionValue')
SFUserReportRequest = _Class('SFUserReportRequest')
SFCardSection = _Class('SFCardSection')
SFVerticalLayoutCardSection = _Class('SFVerticalLayoutCardSection')
SFWorldMapCardSection = _Class('SFWorldMapCardSection')
SFAudioPlaybackCardSection = _Class('SFAudioPlaybackCardSection')
SFSectionHeaderCardSection = _Class('SFSectionHeaderCardSection')
SFFlightCardSection = _Class('SFFlightCardSection')
SFCompactRowCardSection = _Class('SFCompactRowCardSection')
SFAttributionFooterCardSection = _Class('SFAttributionFooterCardSection')
SFHorizontalScrollCardSection = _Class('SFHorizontalScrollCardSection')
SFProductCardSection = _Class('SFProductCardSection')
SFSelectableGridCardSection = _Class('SFSelectableGridCardSection')
SFNullCardSection = _Class('SFNullCardSection')
SFTextColumnsCardSection = _Class('SFTextColumnsCardSection')
SFSocialMediaPostCardSection = _Class('SFSocialMediaPostCardSection')
SFStockChartCardSection = _Class('SFStockChartCardSection')
SFMetaInfoCardSection = _Class('SFMetaInfoCardSection')
SFSuggestionCardSection = _Class('SFSuggestionCardSection')
SFImagesCardSection = _Class('SFImagesCardSection')
SFMapCardSection = _Class('SFMapCardSection')
SFWebCardSection = _Class('SFWebCardSection')
SFMessageCardSection = _Class('SFMessageCardSection')
SFMediaRemoteControlCardSection = _Class('SFMediaRemoteControlCardSection')
SFDetailedRowCardSection = _Class('SFDetailedRowCardSection')
SFMapPlaceCardSection = _Class('SFMapPlaceCardSection')
SFRowCardSection = _Class('SFRowCardSection')
SFButtonCardSection = _Class('SFButtonCardSection')
SFTableRowCardSection = _Class('SFTableRowCardSection')
SFTableHeaderRowCardSection = _Class('SFTableHeaderRowCardSection')
SFHorizontalButtonCardSection = _Class('SFHorizontalButtonCardSection')
SFMediaPlayerCardSection = _Class('SFMediaPlayerCardSection')
SFWatchListCardSection = _Class('SFWatchListCardSection')
SFActivityIndicatorCardSection = _Class('SFActivityIndicatorCardSection')
SFMapsDetailedRowCardSection = _Class('SFMapsDetailedRowCardSection')
SFMediaInfoCardSection = _Class('SFMediaInfoCardSection')
SFKeyValueDataCardSection = _Class('SFKeyValueDataCardSection')
SFTitleCardSection = _Class('SFTitleCardSection')
SFRichTitleCardSection = _Class('SFRichTitleCardSection')
SFScoreboardCardSection = _Class('SFScoreboardCardSection')
SFTrackListCardSection = _Class('SFTrackListCardSection')
SFAppLinkCardSection = _Class('SFAppLinkCardSection')
SFNowPlayingCardSection = _Class('SFNowPlayingCardSection')
SFDescriptionCardSection = _Class('SFDescriptionCardSection')
SFFeedback = _Class('SFFeedback')
SFDidGoToSiteFeedback = _Class('SFDidGoToSiteFeedback')
SFEndSearchFeedback = _Class('SFEndSearchFeedback')
SFEndLocalSearchFeedback = _Class('SFEndLocalSearchFeedback')
SFEndNetworkSearchFeedback = _Class('SFEndNetworkSearchFeedback')
SFStartSearchFeedback = _Class('SFStartSearchFeedback')
SFStartLocalSearchFeedback = _Class('SFStartLocalSearchFeedback')
SFStartNetworkSearchFeedback = _Class('SFStartNetworkSearchFeedback')
SFErrorFeedback = _Class('SFErrorFeedback')
SFLateSectionsAppendedFeedback = _Class('SFLateSectionsAppendedFeedback')
SFDidGoToSearchFeedback = _Class('SFDidGoToSearchFeedback')
SFClientTimingFeedback = _Class('SFClientTimingFeedback')
SFRankingFeedback = _Class('SFRankingFeedback')
SFVisibleSectionHeaderFeedback = _Class('SFVisibleSectionHeaderFeedback')
SFSectionEngagementFeedback = _Class('SFSectionEngagementFeedback')
SFVisibleResultsFeedback = _Class('SFVisibleResultsFeedback')
SFVisibleSuggestionsFeedback = _Class('SFVisibleSuggestionsFeedback')
SFResultRankingFeedback = _Class('SFResultRankingFeedback')
SFCardViewAppearFeedback = _Class('SFCardViewAppearFeedback')
SFCardViewDisappearFeedback = _Class('SFCardViewDisappearFeedback')
SFSuggestionEngagementFeedback = _Class('SFSuggestionEngagementFeedback')
SFResultFeedback = _Class('SFResultFeedback')
SFResultGradingFeedback = _Class('SFResultGradingFeedback')
SFResultEngagementFeedback = _Class('SFResultEngagementFeedback')
SFSearchViewDisappearFeedback = _Class('SFSearchViewDisappearFeedback')
SFSearchViewAppearFeedback = _Class('SFSearchViewAppearFeedback')
SFCustomFeedback = _Class('SFCustomFeedback')
SFClearInputFeedback = _Class('SFClearInputFeedback')
SFSectionRankingFeedback = _Class('SFSectionRankingFeedback')
SFResultsReceivedAfterTimeoutFeedback = _Class('SFResultsReceivedAfterTimeoutFeedback')
SFLookupHintRelevancyFeedback = _Class('SFLookupHintRelevancyFeedback')
SFCardSectionFeedback = _Class('SFCardSectionFeedback')
SFCardSectionEngagementFeedback = _Class('SFCardSectionEngagementFeedback')
SFStoreCardSectionEngagementFeedback = _Class('SFStoreCardSectionEngagementFeedback')
SFMapsCardSectionEngagementFeedback = _Class('SFMapsCardSectionEngagementFeedback')
SFMapCardSectionEngagementFeedback = _Class('SFMapCardSectionEngagementFeedback')
SFUserReportFeedback = _Class('SFUserReportFeedback')
SFSearchResult = _Class('SFSearchResult')
SFActionItem = _Class('SFActionItem')
SFMediaOffer = _Class('SFMediaOffer')
SFText = _Class('SFText')
SFFormattedText = _Class('SFFormattedText')
SFRichText = _Class('SFRichText')
SFImage = _Class('SFImage')
SFSymbolImage = _Class('SFSymbolImage')
SFMonogramImage = _Class('SFMonogramImage')
SFMediaArtworkImage = _Class('SFMediaArtworkImage')
SFContactImage = _Class('SFContactImage')
SFAppIconImage = _Class('SFAppIconImage')
SFCalendarImage = _Class('SFCalendarImage')
SFURLImage = _Class('SFURLImage')
SFLocalImage = _Class('SFLocalImage')
SFMoreResults = _Class('SFMoreResults')
SFCard = _Class('SFCard')