
'''
Classes from the 'SwiftUI' framework.
'''
    
try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None
        
def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None
    
    
SwiftUI.SceneBridge = _Class('SwiftUI.SceneBridge')
SwiftUI.AnyWindowStyleStorageBase = _Class('SwiftUI.AnyWindowStyleStorageBase')
SwiftUI.EmptyViewRendererHost = _Class('SwiftUI.EmptyViewRendererHost')
SwiftUI.DictionaryDecoder = _Class('SwiftUI.DictionaryDecoder')
SwiftUI.DictionaryEncoder = _Class('SwiftUI.DictionaryEncoder')
SwiftUI.ScrollViewNode = _Class('SwiftUI.ScrollViewNode')
SwiftUI.AnyFallbackDelegateBox = _Class('SwiftUI.AnyFallbackDelegateBox')
SwiftUI.SceneStorageTransformBox = _Class('SwiftUI.SceneStorageTransformBox')
SwiftUI.SceneStorageValues = _Class('SwiftUI.SceneStorageValues')
SwiftUI.AnyWindowToolbarStyleStorageBase = _Class('SwiftUI.AnyWindowToolbarStyleStorageBase')
SwiftUI.MainMenuItemHost = _Class('SwiftUI.MainMenuItemHost')
SwiftUI.AnyResolvedPaint = _Class('SwiftUI.AnyResolvedPaint')
SwiftUI.RBGraphicsContext = _Class('SwiftUI.RBGraphicsContext')
SwiftUI.MemoizedGraphicsDrawingCallback = _Class('SwiftUI.MemoizedGraphicsDrawingCallback')
SwiftUI.ArchiveReader = _Class('SwiftUI.ArchiveReader')
SwiftUI.DataArchiveReader = _Class('SwiftUI.DataArchiveReader')
SwiftUI.FileArchiveReader = _Class('SwiftUI.FileArchiveReader')
SwiftUI.ArchiveWriter = _Class('SwiftUI.ArchiveWriter')
SwiftUI.DataArchiveWriter = _Class('SwiftUI.DataArchiveWriter')
SwiftUI.FileArchiveWriter = _Class('SwiftUI.FileArchiveWriter')
SwiftUI.ChildIndexProjection = _Class('SwiftUI.ChildIndexProjection')
SwiftUI._PreviewHost = _Class('SwiftUI._PreviewHost')
SwiftUI.ScrollTest = _Class('SwiftUI.ScrollTest')
SwiftUI.WidgetBundleHost = _Class('SwiftUI.WidgetBundleHost')
SwiftUI.UIBarItemTarget = _Class('SwiftUI.UIBarItemTarget')
SwiftUI.RootViewDelegate = _Class('SwiftUI.RootViewDelegate')
SwiftUI.DisplayLink = _Class('SwiftUI.DisplayLink')
SwiftUI.AnyTextModifier = _Class('SwiftUI.AnyTextModifier')
SwiftUI.BoldTextModifier = _Class('SwiftUI.BoldTextModifier')
SwiftUI.CGGraphicsContext = _Class('SwiftUI.CGGraphicsContext')
SwiftUI.AnimationBoxBase = _Class('SwiftUI.AnimationBoxBase')
SwiftUI._ViewList_IndirectMap = _Class('SwiftUI._ViewList_IndirectMap')
SwiftUI.AnyImageProviderBox = _Class('SwiftUI.AnyImageProviderBox')
SwiftUI.AnyTransitionBox = _Class('SwiftUI.AnyTransitionBox')
SwiftUI.ResolvedStyledText = _Class('SwiftUI.ResolvedStyledText')
SwiftUI.PreferenceBridge = _Class('SwiftUI.PreferenceBridge')
SwiftUI.AnyFontBox = _Class('SwiftUI.AnyFontBox')
SwiftUI.AnyTextStorage = _Class('SwiftUI.AnyTextStorage')
SwiftUI._ViewList_Subgraph = _Class('SwiftUI._ViewList_Subgraph')
SwiftUI.AccessibilityRelationshipScope = _Class('SwiftUI.AccessibilityRelationshipScope')
SwiftUI.AnyColorBox = _Class('SwiftUI.AnyColorBox')
SwiftUI.AnyViewStorageBase = _Class('SwiftUI.AnyViewStorageBase')
SwiftUI.AnyLocationBase = _Class('SwiftUI.AnyLocationBase')
SwiftUI.EventBindingBridge = _Class('SwiftUI.EventBindingBridge')
SwiftUI.UIKitEventBindingBridge = _Class('SwiftUI.UIKitEventBindingBridge')
SwiftUI.EventBindingManager = _Class('SwiftUI.EventBindingManager')
SwiftUI.StyledTextLayoutDelegate = _Class('SwiftUI.StyledTextLayoutDelegate')
SwiftUI.ResolvedImageLayoutDelegate = _Class('SwiftUI.ResolvedImageLayoutDelegate')
SwiftUI.ViewResponder = _Class('SwiftUI.ViewResponder')
SwiftUI.UnaryViewResponder = _Class('SwiftUI.UnaryViewResponder')
SwiftUI.UIViewResponder = _Class('SwiftUI.UIViewResponder')
SwiftUI.HostingScrollViewResponder = _Class('SwiftUI.HostingScrollViewResponder')
SwiftUI.MultiViewResponder = _Class('SwiftUI.MultiViewResponder')
SwiftUI.DefaultLayoutViewResponder = _Class('SwiftUI.DefaultLayoutViewResponder')
SwiftUI.FocusNamespaceViewResponder = _Class('SwiftUI.FocusNamespaceViewResponder')
SwiftUI.DropViewResponder = _Class('SwiftUI.DropViewResponder')
SwiftUI.UIViewSnapshotResponder = _Class('SwiftUI.UIViewSnapshotResponder')
SwiftUI.ContextMenuResponder = _Class('SwiftUI.ContextMenuResponder')
SwiftUI.HoverResponder = _Class('SwiftUI.HoverResponder')
SwiftUI.DragViewResponder = _Class('SwiftUI.DragViewResponder')
SwiftUI.GraphHost = _Class('SwiftUI.GraphHost')
SwiftUI.WidgetGraph = _Class('SwiftUI.WidgetGraph')
SwiftUI._WidgetGraph = _Class('SwiftUI._WidgetGraph')
SwiftUI.AppGraph = _Class('SwiftUI.AppGraph')
SwiftUI.ViewGraph = _Class('SwiftUI.ViewGraph')
SwiftUI.FocusBridge = _Class('SwiftUI.FocusBridge')
SwiftUI.UserActivityTrackingInfo = _Class('SwiftUI.UserActivityTrackingInfo')
SwiftUI.InteropResponder = _Class('SwiftUI.InteropResponder')
SwiftUI.KeyboardShortcutBridge = _Class('SwiftUI.KeyboardShortcutBridge')
SwiftUI.ObjcColor = _Class('SwiftUI.ObjcColor')
SwiftUI.AccessibilityNode = _Class('SwiftUI.AccessibilityNode')
SwiftUI.AccessibilityReadingContentNode = _Class('SwiftUI.AccessibilityReadingContentNode')
BaseDateProvider = _Class('BaseDateProvider')
TimeProvider = _Class('TimeProvider')
RelativeDateProvider = _Class('RelativeDateProvider')
TimeIntervalProvider = _Class('TimeIntervalProvider')
DateProvider = _Class('DateProvider')
SwiftUI.PlatformDocument = _Class('SwiftUI.PlatformDocument')
SwiftUIEnvironmentWrapper = _Class('SwiftUIEnvironmentWrapper')
SwiftUI.PlatformViewCoordinator = _Class('SwiftUI.PlatformViewCoordinator')
SwiftUI.UIKitPopUpButtonCoordinator = _Class('SwiftUI.UIKitPopUpButtonCoordinator')
SwiftUI.FileImportExportBridge = _Class('SwiftUI.FileImportExportBridge')
SwiftUI.UIKitToolbarCoordinator = _Class('SwiftUI.UIKitToolbarCoordinator')
SwiftUI.DocumentNavigationItem = _Class('SwiftUI.DocumentNavigationItem')
SwiftUI.SwiftUITabBarItem = _Class('SwiftUI.SwiftUITabBarItem')
SwiftUI.UIKitGestureRecognizer = _Class('SwiftUI.UIKitGestureRecognizer')
SwiftUI.GradientLayer = _Class('SwiftUI.GradientLayer')
SwiftUI.ImageLayer = _Class('SwiftUI.ImageLayer')
SwiftUI.MaskLayer = _Class('SwiftUI.MaskLayer')
SwiftUI.AppSceneDelegate = _Class('SwiftUI.AppSceneDelegate')
SwiftUI.AppDelegate = _Class('SwiftUI.AppDelegate')
SwiftUI.TestingSceneDelegate = _Class('SwiftUI.TestingSceneDelegate')
SwiftUI.TestingAppDelegate = _Class('SwiftUI.TestingAppDelegate')
SwiftUI.UIKitMainMenuController = _Class('SwiftUI.UIKitMainMenuController')
SwiftUI._UIGraphicsView = _Class('SwiftUI._UIGraphicsView')
SwiftUI.RenderBoxView = _Class('SwiftUI.RenderBoxView')
SwiftUI.ListCoreHeaderHost = _Class('SwiftUI.ListCoreHeaderHost')
SwiftUI.ListCoreCellHost = _Class('SwiftUI.ListCoreCellHost')
SwiftUI.SwiftUIToolbar = _Class('SwiftUI.SwiftUIToolbar')
SwiftUI.HostingScrollView = _Class('SwiftUI.HostingScrollView')
SwiftUI.SwiftUITextField = _Class('SwiftUI.SwiftUITextField')
SwiftUI.PlatformAlertController = _Class('SwiftUI.PlatformAlertController')
SwiftUI.NotificationSendingSplitViewController = _Class('SwiftUI.NotificationSendingSplitViewController')
SwiftUI.NotifyingMulticolumnSplitViewController = _Class('SwiftUI.NotifyingMulticolumnSplitViewController')
SwiftUI.SplitViewNavigationController = _Class('SwiftUI.SplitViewNavigationController')
SwiftUI.DocumentBrowserViewController = _Class('SwiftUI.DocumentBrowserViewController')