
'''
Classes from the 'UIFoundation' framework.
'''
    
try:
    from rubicon.objc import ObjCClass
except ValueError:
    def ObjCClass(name):
        return None
        
def _Class(name):
    try:
        return ObjCClass(name)
    except NameError:
        return None
    
    
NSTextSelection = _Class('NSTextSelection')
NSRTFWriter = _Class('NSRTFWriter')
NSHTMLWriter = _Class('NSHTMLWriter')
NSHTMLReader = _Class('NSHTMLReader')
NSHTMLWebDelegate = _Class('NSHTMLWebDelegate')
NSSubstituteWebResource = _Class('NSSubstituteWebResource')
NSTextCorrectionMarkerRendering = _Class('NSTextCorrectionMarkerRendering')
NSRTFReader = _Class('NSRTFReader')
NSRTFReaderTableState = _Class('NSRTFReaderTableState')
NSTextAttachmentViewProvider = _Class('NSTextAttachmentViewProvider')
NSTextViewportLayoutController = _Class('NSTextViewportLayoutController')
UIPointFIFO = _Class('UIPointFIFO')
UIQuadCurvePointFIFO = _Class('UIQuadCurvePointFIFO')
UIBoxcarFilterPointFIFO = _Class('UIBoxcarFilterPointFIFO')
NSTextBlock = _Class('NSTextBlock')
NSTextTable = _Class('NSTextTable')
NSTextTableBlock = _Class('NSTextTableBlock')
NSTextBlockLayoutHelper = _Class('NSTextBlockLayoutHelper')
NSTextList = _Class('NSTextList')
NSStringDrawingTextStorageSettings = _Class('NSStringDrawingTextStorageSettings')
NSTextContentManager = _Class('NSTextContentManager')
NSTextContentStorage = _Class('NSTextContentStorage')
NSTextLineFragment = _Class('NSTextLineFragment')
NSCountableTextLocation = _Class('NSCountableTextLocation')
NSTextRange = _Class('NSTextRange')
NSCountableTextRange = _Class('NSCountableTextRange')
NSLayoutManagerTextBlockRowArrayCache = _Class('NSLayoutManagerTextBlockRowArrayCache')
NSLayoutManagerTextBlockHelper = _Class('NSLayoutManagerTextBlockHelper')
NSTextAlternatives = _Class('NSTextAlternatives')
NSTextElement = _Class('NSTextElement')
NSTextParagraph = _Class('NSTextParagraph')
NSGlyphInfo = _Class('NSGlyphInfo')
NSCTGlyphInfo = _Class('NSCTGlyphInfo')
NSCIDGlyphInfo = _Class('NSCIDGlyphInfo')
NSIdentityGlyphInfo = _Class('NSIdentityGlyphInfo')
NSGlyphNameGlyphInfo = _Class('NSGlyphNameGlyphInfo')
UINibCoderValue = _Class('UINibCoderValue')
NSTextLayoutManager = _Class('NSTextLayoutManager')
NSTextSelectionNavigation = _Class('NSTextSelectionNavigation')
NSLineFragmentRenderingContext = _Class('NSLineFragmentRenderingContext')
NSTextLayoutFragment = _Class('NSTextLayoutFragment')
NSTextGraphicsContextProvider = _Class('NSTextGraphicsContextProvider')
NSTextAttachment = _Class('NSTextAttachment')
NSTextTab = _Class('NSTextTab')
NSDataAsset = _Class('NSDataAsset')
NSInsertionPointHelper = _Class('NSInsertionPointHelper')
NSATSGlyphStorage = _Class('NSATSGlyphStorage')
NSATSLineFragment = _Class('NSATSLineFragment')
NSGlyphGenerator = _Class('NSGlyphGenerator')
NSTextContainer = _Class('NSTextContainer')
NSParagraphArbitrator = _Class('NSParagraphArbitrator')
NSExtraLMData = _Class('NSExtraLMData')
NSRunStorage = _Class('NSRunStorage')
NSIdRunStorage = _Class('NSIdRunStorage')
NSStorage = _Class('NSStorage')
UINibStringIDTable = _Class('UINibStringIDTable')
NSLayoutManager = _Class('NSLayoutManager')
NSTypesetter = _Class('NSTypesetter')
NSATSTypesetter = _Class('NSATSTypesetter')
NSSingleLineTypesetter = _Class('NSSingleLineTypesetter')
NSCoreTypesetter = _Class('NSCoreTypesetter')
NSStringDrawingContext = _Class('NSStringDrawingContext')
NSShadow = _Class('NSShadow')
NSParagraphStyleExtraData = _Class('NSParagraphStyleExtraData')
UIFontDescriptor = _Class('UIFontDescriptor')
UICTFontDescriptor = _Class('UICTFontDescriptor')
UIFont = _Class('UIFont')
NSFont = _Class('NSFont')
UICTFont = _Class('UICTFont')
NSParagraphStyle = _Class('NSParagraphStyle')
NSMutableParagraphStyle = _Class('NSMutableParagraphStyle')
UINibEncoder = _Class('UINibEncoder')
UINibDecoder = _Class('UINibDecoder')
NSAttributeDictionaryEnumerator = _Class('NSAttributeDictionaryEnumerator')
NSConcreteNotifyingMutableAttributedString = _Class('NSConcreteNotifyingMutableAttributedString')
NSTextStorage = _Class('NSTextStorage')
NSConcreteTextStorage = _Class('NSConcreteTextStorage')
NSStringDrawingTextStorage = _Class('NSStringDrawingTextStorage')
NSAttributeDictionary = _Class('NSAttributeDictionary')
NSTempAttributeDictionary = _Class('NSTempAttributeDictionary')